package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Balance extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int balanceid;
     private int userid;
     private Date date;
     private double amt;
     private double currentbalance;
     private String description;
     private int optionalresponseid;
     private boolean isresearchermoney;
     private boolean isbloggermoney;

    public static Balance get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Balance");
        try {
            logger.debug("Balance.get(" + id + ") called.");
            Balance obj = (Balance) HibernateUtil.getSession().get(Balance.class, id);
            if (obj == null) {
                logger.debug("Balance.get(" + id + ") returning new instance because hibernate returned null.");
                return new Balance();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Balance", ex);
            return new Balance();
        }
    }

    // Constructors

    /** default constructor */
    public Balance() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors


    public int getBalanceid() {
        return balanceid;
    }

    public void setBalanceid(int balanceid) {
        this.balanceid = balanceid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public double getAmt() {
        return amt;
    }

    public void setAmt(double amt) {
        this.amt = amt;
    }

    public double getCurrentbalance() {
        return currentbalance;
    }

    public void setCurrentbalance(double currentbalance) {
        this.currentbalance = currentbalance;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getOptionalresponseid() {
        return optionalresponseid;
    }

    public void setOptionalresponseid(int optionalresponseid) {
        this.optionalresponseid = optionalresponseid;
    }


    public boolean getIsresearchermoney() {
        return isresearchermoney;
    }

    public void setIsresearchermoney(boolean isresearchermoney) {
        this.isresearchermoney=isresearchermoney;
    }

    public boolean getIsbloggermoney() {
        return isbloggermoney;
    }

    public void setIsbloggermoney(boolean isbloggermoney) {
        this.isbloggermoney=isbloggermoney;
    }
}
