package com.dneero.dao;

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:22 PM by Hibernate Tools 3.1.0.beta4



/**
 * Bloggeraddress generated by hbm2java
 */

public class Bloggeraddress extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields    

     private int bloggeraddressid;
     private int bloggerid;
     private int addressid;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Bloggeraddress get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Bloggeraddress");
        try {
            logger.debug("Bloggeraddress.get(" + id + ") called.");
            Bloggeraddress obj = (Bloggeraddress) HibernateUtil.getSession().get(Bloggeraddress.class, id);
            if (obj == null) {
                logger.debug("Bloggeraddress.get(" + id + ") returning new instance because hibernate returned null.");
                return new Bloggeraddress();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Bloggeraddress", ex);
            return new Bloggeraddress();
        }
    }

    // Constructors

    /** default constructor */
    public Bloggeraddress() {
    }

    
    /** full constructor */
    public Bloggeraddress(int bloggeraddressid, int bloggerid, int addressid) {
        this.bloggeraddressid = bloggeraddressid;
        this.bloggerid = bloggerid;
        this.addressid = addressid;
    }
    

   
    // Property accessors

    public int getBloggeraddressid() {
        return this.bloggeraddressid;
    }
    
    public void setBloggeraddressid(int bloggeraddressid) {
        this.bloggeraddressid = bloggeraddressid;
    }

    public int getBloggerid() {
        return this.bloggerid;
    }
    
    public void setBloggerid(int bloggerid) {
        this.bloggerid = bloggerid;
    }

    public int getAddressid() {
        return this.addressid;
    }
    
    public void setAddressid(int addressid) {
        this.addressid = addressid;
    }
   








}
