package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import com.dneero.session.AuthControlled;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Blog extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields
     private int blogid;
     private int bloggerid;
     private String url;
     private String title;
     private String blogfocus;
     private double quality;
     private double quality90days;
     private Set<Impression> impressions = new HashSet<Impression>();

    //Validator
    public void validateRegerEntity() throws GeneralException {
        
    }

    //Loader
    public void load(){

    }

    public static Blog get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Blog");
        try {
            logger.debug("Blog.get(" + id + ") called.");
            Blog obj = (Blog) HibernateUtil.getSession().get(Blog.class, id);
            if (obj == null) {
                logger.debug("Blog.get(" + id + ") returning new instance because hibernate returned null.");
                return new Blog();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Blog", ex);
            return new Blog();
        }
    }

    // Constructors

    /** default constructor */
    public Blog() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==Blogger.get(bloggerid).getUserid()){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getBlogid() {
        return blogid;
    }

    public void setBlogid(int blogid) {
        this.blogid = blogid;
    }

    public int getBloggerid() {
        return bloggerid;
    }

    public void setBloggerid(int bloggerid) {
        this.bloggerid = bloggerid;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBlogfocus() {
        return blogfocus;
    }

    public void setBlogfocus(String blogfocus) {
        this.blogfocus = blogfocus;
    }

    public Set<Impression> getImpressions() {
        return impressions;
    }

    public void setImpressions(Set<Impression> impressions) {
        this.impressions = impressions;
    }

    public double getQuality() {
        return quality;
    }

    public void setQuality(double quality) {
        this.quality = quality;
    }

    public double getQuality90days() {
        return quality90days;
    }

    public void setQuality90days(double quality90days) {
        this.quality90days = quality90days;
    }
}
