package com.dneero.dao;

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:23 PM by Hibernate Tools 3.1.0.beta4



/**
 * Blogger generated by hbm2java
 */

public class Blogger extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields    

     private int bloggerid;
     private int age;
     private int gender;
     private int ethnicity;
     private int maritalstatus;
     private int incomerange;
     private int educationlevel;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Blogger get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Blogger");
        try {
            logger.debug("Blogger.get(" + id + ") called.");
            Blogger obj = (Blogger) HibernateUtil.getSession().get(Blogger.class, id);
            if (obj == null) {
                logger.debug("Blogger.get(" + id + ") returning new instance because hibernate returned null.");
                return new Blogger();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Blogger", ex);
            return new Blogger();
        }
    }

    // Constructors

    /** default constructor */
    public Blogger() {
    }

    
    /** full constructor */
    public Blogger(int bloggerid, int age, int gender, int ethnicity, int maritalstatus, int incomerange, int educationlevel) {
        this.bloggerid = bloggerid;
        this.age = age;
        this.gender = gender;
        this.ethnicity = ethnicity;
        this.maritalstatus = maritalstatus;
        this.incomerange = incomerange;
        this.educationlevel = educationlevel;
    }
    

   
    // Property accessors

    public int getBloggerid() {
        return this.bloggerid;
    }
    
    public void setBloggerid(int bloggerid) {
        this.bloggerid = bloggerid;
    }

    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    public int getGender() {
        return this.gender;
    }
    
    public void setGender(int gender) {
        this.gender = gender;
    }

    public int getEthnicity() {
        return this.ethnicity;
    }
    
    public void setEthnicity(int ethnicity) {
        this.ethnicity = ethnicity;
    }

    public int getMaritalstatus() {
        return this.maritalstatus;
    }
    
    public void setMaritalstatus(int maritalstatus) {
        this.maritalstatus = maritalstatus;
    }

    public int getIncomerange() {
        return this.incomerange;
    }
    
    public void setIncomerange(int incomerange) {
        this.incomerange = incomerange;
    }

    public int getEducationlevel() {
        return this.educationlevel;
    }
    
    public void setEducationlevel(int educationlevel) {
        this.educationlevel = educationlevel;
    }
   








}
