package com.dneero.dao;

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:24 PM by Hibernate Tools 3.1.0.beta4



/**
 * Blogsite generated by hbm2java
 */

public class Blogsite extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields    

     private int blogsiteid;
     private int bloggerid;
     private String url;
     private String sitetitle;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Blogsite get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Blogsite");
        try {
            logger.debug("Blogsite.get(" + id + ") called.");
            Blogsite obj = (Blogsite) HibernateUtil.getSession().get(Blogsite.class, id);
            if (obj == null) {
                logger.debug("Blogsite.get(" + id + ") returning new instance because hibernate returned null.");
                return new Blogsite();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Blogsite", ex);
            return new Blogsite();
        }
    }

    // Constructors

    /** default constructor */
    public Blogsite() {
    }

    
    /** full constructor */
    public Blogsite(int blogsiteid, int bloggerid, String url, String sitetitle) {
        this.blogsiteid = blogsiteid;
        this.bloggerid = bloggerid;
        this.url = url;
        this.sitetitle = sitetitle;
    }
    

   
    // Property accessors

    public int getBlogsiteid() {
        return this.blogsiteid;
    }
    
    public void setBlogsiteid(int blogsiteid) {
        this.blogsiteid = blogsiteid;
    }

    public int getBloggerid() {
        return this.bloggerid;
    }
    
    public void setBloggerid(int bloggerid) {
        this.bloggerid = bloggerid;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getSitetitle() {
        return this.sitetitle;
    }
    
    public void setSitetitle(String sitetitle) {
        this.sitetitle = sitetitle;
    }
   








}
