package com.dneero.dao;
// Generated Apr 17, 2006 3:45:26 PM by Hibernate Tools 3.1.0.beta4

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;

import java.util.Date;

import org.apache.log4j.Logger;


/**
 * Blogpost generated by hbm2java
 */

public class Blogpost extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields    

     private int blogpostid;
     private String url;
     private Date whencollected;
     private boolean isavailableforsale;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Blogpost get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Blogpost");
        try {
            logger.debug("Blogpost.get(" + id + ") called.");
            Blogpost obj = (Blogpost) HibernateUtil.getSession().get(Blogpost.class, id);
            if (obj == null) {
                logger.debug("Blogpost.get(" + id + ") returning new instance because hibernate returned null.");
                return new Blogpost();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Blogpost", ex);
            return new Blogpost();
        }
    }

    // Constructors

    /** default constructor */
    public Blogpost() {
    }


    /** full constructor */
    public Blogpost(int blogpostid, String url, Date whencollected, boolean isavailableforsale) {
        this.blogpostid = blogpostid;
        this.url = url;
        this.whencollected = whencollected;
        this.isavailableforsale = isavailableforsale;
    }



    // Property accessors

    public int getBlogpostid() {
        return this.blogpostid;
    }

    public void setBlogpostid(int blogpostid) {
        this.blogpostid = blogpostid;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Date getWhencollected() {
        return this.whencollected;
    }

    public void setWhencollected(Date whencollected) {
        this.whencollected = whencollected;
    }

    public boolean isIsavailableforsale() {
        return this.isavailableforsale;
    }

    public void setIsavailableforsale(boolean isavailableforsale) {
        this.isavailableforsale = isavailableforsale;
    }









}
