package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Couponredemption extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    //Fields
    private int couponredemptionid;
    private int couponid;
    private int userid;
    private int surveyid;
    private Date date;


    public static Couponredemption get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Couponredemption");
        try {
            logger.debug("Couponredemption.get(" + id + ") called.");
            Couponredemption obj = (Couponredemption) HibernateUtil.getSession().get(Couponredemption.class, id);
            if (obj == null) {
                logger.debug("Couponredemption.get(" + id + ") returning new instance because hibernate returned null.");
                return new Couponredemption();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Couponredemption", ex);
            return new Couponredemption();
        }
    }

    // Constructors

    /** default constructor */
    public Couponredemption() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getCouponredemptionid() {
        return couponredemptionid;
    }

    public void setCouponredemptionid(int couponredemptionid) {
        this.couponredemptionid = couponredemptionid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    public int getSurveyid() {
        return surveyid;
    }

    public void setSurveyid(int surveyid) {
        this.surveyid = surveyid;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public int getCouponid() {
        return couponid;
    }

    public void setCouponid(int couponid) {
        this.couponid = couponid;
    }
}
