package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Coupon extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    //Fields
    private int couponid;
    private String name;
    private String description;
    private String couponcode;
    private double discountpercent;
    private Date startdate;
    private Date enddate;
    private int timescanberedeemed;
    private String commaseplistofuserids;


    public static Coupon get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Coupon");
        try {
            logger.debug("Coupon.get(" + id + ") called.");
            Coupon obj = (Coupon) HibernateUtil.getSession().get(Coupon.class, id);
            if (obj == null) {
                logger.debug("Coupon.get(" + id + ") returning new instance because hibernate returned null.");
                return new Coupon();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Coupon", ex);
            return new Coupon();
        }
    }

    // Constructors

    /** default constructor */
    public Coupon() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors
    public int getCouponid() {
        return couponid;
    }

    public void setCouponid(int couponid) {
        this.couponid = couponid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getStartdate() {
        return startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEnddate() {
        return enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public int getTimescanberedeemed() {
        return timescanberedeemed;
    }

    public void setTimescanberedeemed(int timescanberedeemed) {
        this.timescanberedeemed = timescanberedeemed;
    }

    public String getCommaseplistofuserids() {
        return commaseplistofuserids;
    }

    public void setCommaseplistofuserids(String commaseplistofuserids) {
        this.commaseplistofuserids = commaseplistofuserids;
    }

    public double getDiscountpercent() {
        return discountpercent;
    }

    public void setDiscountpercent(double discountpercent) {
        this.discountpercent = discountpercent;
    }

    public String getCouponcode() {
        return couponcode;
    }

    public void setCouponcode(String couponcode) {
        this.couponcode = couponcode;
    }
}
