package com.dneero.dao;

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:25 PM by Hibernate Tools 3.1.0.beta4



/**
 * Datausageevent generated by hbm2java
 */

public class Datausageevent extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields    

     private int datausageeventid;
     private int blogpostid;
     private int usageeventtypeid;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Datausageevent get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Datausageevent");
        try {
            logger.debug("Datausageevent.get(" + id + ") called.");
            Datausageevent obj = (Datausageevent) HibernateUtil.getSession().get(Datausageevent.class, id);
            if (obj == null) {
                logger.debug("Datausageevent.get(" + id + ") returning new instance because hibernate returned null.");
                return new Datausageevent();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Datausageevent", ex);
            return new Datausageevent();
        }
    }

    // Constructors

    /** default constructor */
    public Datausageevent() {
    }

    
    /** full constructor */
    public Datausageevent(int datausageeventid, int blogpostid, int usageeventtypeid) {
        this.datausageeventid = datausageeventid;
        this.blogpostid = blogpostid;
        this.usageeventtypeid = usageeventtypeid;
    }
    

   
    // Property accessors

    public int getDatausageeventid() {
        return this.datausageeventid;
    }
    
    public void setDatausageeventid(int datausageeventid) {
        this.datausageeventid = datausageeventid;
    }

    public int getBlogpostid() {
        return this.blogpostid;
    }
    
    public void setBlogpostid(int blogpostid) {
        this.blogpostid = blogpostid;
    }

    public int getUsageeventtypeid() {
        return this.usageeventtypeid;
    }
    
    public void setUsageeventtypeid(int usageeventtypeid) {
        this.usageeventtypeid = usageeventtypeid;
    }
   








}
