package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Demographic extends BasePersistentClass implements java.io.Serializable, AuthControlled {

    public static int TYPE_SELECT = 1;
    public static int TYPE_TEXT = 2;

    // Fields
    private int demographicid;
    private int plid;
    private String name;
    private String possiblevalues;
    private String description;
    private int ordernum;
    private int type;
    private boolean isrequired;


    public static Demographic get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Demographic");
        try {
            logger.debug("Demographic.get(" + id + ") called.");
            Demographic obj = (Demographic) HibernateUtil.getSession().get(Demographic.class, id);
            if (obj == null) {
                logger.debug("Demographic.get(" + id + ") returning new instance because hibernate returned null.");
                return new Demographic();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Demographic", ex);
            return new Demographic();
        }
    }


    // Constructors

    /** default constructor */
    public Demographic() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors


    public int getDemographicid() {
        return demographicid;
    }

    public void setDemographicid(int demographicid) {
        this.demographicid = demographicid;
    }

    public int getPlid() {
        return plid;
    }

    public void setPlid(int plid) {
        this.plid = plid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPossiblevalues() {
        return possiblevalues;
    }

    public void setPossiblevalues(String possiblevalues) {
        this.possiblevalues = possiblevalues;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getOrdernum() {
        return ordernum;
    }

    public void setOrdernum(int ordernum) {
        this.ordernum = ordernum;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public boolean getIsrequired() {
        return isrequired;
    }

    public void setIsrequired(boolean isrequired) {
        this.isrequired = isrequired;
    }
}