package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Errorlogging extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int errorloggingid;
     private String classname;
    private String level;



    public static Errorlogging get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Errorlogging");
        try {
            logger.debug("Errorlogging.get(" + id + ") called.");
            Errorlogging obj = (Errorlogging) HibernateUtil.getSession().get(Errorlogging.class, id);
            if (obj == null) {
                logger.debug("Errorlogging.get(" + id + ") returning new instance because hibernate returned null.");
                return new Errorlogging();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Errorlogging", ex);
            return new Errorlogging();
        }
    }

    // Constructors

    /** default constructor */
    public Errorlogging() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getErrorloggingid() {
        return errorloggingid;
    }

    public void setErrorloggingid(int errorloggingid) {
        this.errorloggingid=errorloggingid;
    }

    public String getClassname() {
        return classname;
    }

    public void setClassname(String classname) {
        this.classname=classname;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level=level;
    }
}