package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import com.dneero.util.GeneralException;

import java.util.Set;
import java.util.HashSet;
import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Eula extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields
     private int eulaid;
     private String eula;
     private Date date;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Eula get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Eula");
        try {
            logger.debug("Eula.get(" + id + ") called.");
            Eula obj = (Eula) HibernateUtil.getSession().get(Eula.class, id);
            if (obj == null) {
                logger.debug("Eula.get(" + id + ") returning new instance because hibernate returned null.");
                return new Eula();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Eula", ex);
            return new Eula();
        }
    }

    // Constructors

    /** default constructor */
    public Eula() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors


    public int getEulaid() {
        return eulaid;
    }

    public void setEulaid(int eulaid) {
        this.eulaid = eulaid;
    }

    public String getEula() {
        return eula;
    }

    public void setEula(String eula) {
        this.eula = eula;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
}
