package com.dneero.dao;

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:23 PM by Hibernate Tools 3.1.0.beta4



/**
 * Format generated by hbm2java
 */

public class Format extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields    

     private int formatid;
     private String format;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Format get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Format");
        try {
            logger.debug("Format.get(" + id + ") called.");
            Format obj = (Format) HibernateUtil.getSession().get(Format.class, id);
            if (obj == null) {
                logger.debug("Format.get(" + id + ") returning new instance because hibernate returned null.");
                return new Format();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Format", ex);
            return new Format();
        }
    }

    // Constructors

    /** default constructor */
    public Format() {
    }

    
    /** full constructor */
    public Format(int formatid, String format) {
        this.formatid = formatid;
        this.format = format;
    }
    

   
    // Property accessors

    public int getFormatid() {
        return this.formatid;
    }
    
    public void setFormatid(int formatid) {
        this.formatid = formatid;
    }

    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
   








}
