package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Impressiondetail extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields
     private int impressiondetailid;
     private int impressionid;
     private Date impressiondate;
     private String ip;



    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Impressiondetail get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Impressiondetail");
        try {
            logger.debug("Impressiondetail.get(" + id + ") called.");
            Impressiondetail obj = (Impressiondetail) HibernateUtil.getSession().get(Impressiondetail.class, id);
            if (obj == null) {
                logger.debug("Impressiondetail.get(" + id + ") returning new instance because hibernate returned null.");
                return new Impressiondetail();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Impressiondetail", ex);
            return new Impressiondetail();
        }
    }

    // Constructors

    /** default constructor */
    public Impressiondetail() {
    }






    // Property accessors

    public int getImpressiondetailid() {
        return impressiondetailid;
    }

    public void setImpressiondetailid(int impressiondetailid) {
        this.impressiondetailid = impressiondetailid;
    }

    public int getImpressionid() {
        return impressionid;
    }

    public void setImpressionid(int impressionid) {
        this.impressionid = impressionid;
    }

    public Date getImpressiondate() {
        return impressiondate;
    }

    public void setImpressiondate(Date impressiondate) {
        this.impressiondate = impressiondate;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

}
