package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import com.dneero.session.AuthControlled;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Impressionpaymentgroup extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {

    // Fields
     private int impressionpaymentgroupid;
     private int bloggerid;
     private Date date;
     private double amt;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Impressionpaymentgroup get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Impressionpaymentgroup");
        try {
            logger.debug("Impressionpaymentgroup.get(" + id + ") called.");
            Impressionpaymentgroup obj = (Impressionpaymentgroup) HibernateUtil.getSession().get(Impressionpaymentgroup.class, id);
            if (obj == null) {
                logger.debug("Impressionpaymentgroup.get(" + id + ") returning new instance because hibernate returned null.");
                return new Impressionpaymentgroup();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Impressionpaymentgroup", ex);
            return new Impressionpaymentgroup();
        }
    }

    // Constructors

    /** default constructor */
    public Impressionpaymentgroup() {
    }


    public boolean canRead(User user){
        if (user.getUserid()==Blogger.get(bloggerid).getUserid()){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }


    // Property accessors

    public int getImpressionpaymentgroupid() {
        return impressionpaymentgroupid;
    }

    public void setImpressionpaymentgroupid(int impressionpaymentgroupid) {
        this.impressionpaymentgroupid = impressionpaymentgroupid;
    }

    public int getBloggerid() {
        return bloggerid;
    }

    public void setBloggerid(int bloggerid) {
        this.bloggerid = bloggerid;
    }


    public double getAmt() {
        return amt;
    }

    public void setAmt(double amt) {
        this.amt = amt;
    }

  

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }


}
