package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Impressiondetail extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields
     private int impressiondetailid;
     private int impressionid;
     private int invoiceid;
     private int bloggerid;
     private int paybloggerid;
     private Date impressiondate;
     private String ip;
     private int qualifiesforpaymentstatus;

     public static int QUALIFIESFORPAYMENTSTATUS_PENDING = -1;
     public static int QUALIFIESFORPAYMENTSTATUS_FALSE = 0;
     public static int QUALIFIESFORPAYMENTSTATUS_TRUE = 1;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Impressiondetail get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Impressiondetail");
        try {
            logger.debug("Impressiondetail.get(" + id + ") called.");
            Impressiondetail obj = (Impressiondetail) HibernateUtil.getSession().get(Impressiondetail.class, id);
            if (obj == null) {
                logger.debug("Impressiondetail.get(" + id + ") returning new instance because hibernate returned null.");
                return new Impressiondetail();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Impressiondetail", ex);
            return new Impressiondetail();
        }
    }

    // Constructors

    /** default constructor */
    public Impressiondetail() {
    }

    public boolean canRead(User user){
        Impression impression = Impression.get(impressionid);
        return impression.canRead(user);
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getImpressiondetailid() {
        return impressiondetailid;
    }

    public void setImpressiondetailid(int impressiondetailid) {
        this.impressiondetailid = impressiondetailid;
    }

    public int getImpressionid() {
        return impressionid;
    }

    public void setImpressionid(int impressionid) {
        this.impressionid = impressionid;
    }

    public Date getImpressiondate() {
        return impressiondate;
    }

    public void setImpressiondate(Date impressiondate) {
        this.impressiondate = impressiondate;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public int getInvoiceid() {
        return invoiceid;
    }

    public void setInvoiceid(int invoiceid) {
        this.invoiceid = invoiceid;
    }

    public int getPaybloggerid() {
        return paybloggerid;
    }

    public void setPaybloggerid(int paybloggerid) {
        this.paybloggerid = paybloggerid;
    }

    public int getBloggerid() {
        return bloggerid;
    }

    public void setBloggerid(int bloggerid) {
        this.bloggerid = bloggerid;
    }

    public int getQualifiesforpaymentstatus() {
        return qualifiesforpaymentstatus;
    }

    public void setQualifiesforpaymentstatus(int qualifiesforpaymentstatus) {
        this.qualifiesforpaymentstatus = qualifiesforpaymentstatus;
    }
}
