package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Impression extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int impressionid;
     private int userid;
     private int responseid;
     private int surveyid;
     private String referer;
     private int impressionstotal;
     private int impressionstobepaid;
     private int impressionspaid;
     private String impressionsbyday;
     private int quality;
     private Date firstseen;




    public static Impression get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Impression");
        try {
            logger.debug("Impression.get(" + id + ") called.");
            Impression obj = (Impression) HibernateUtil.getSession().get(Impression.class, id);
            if (obj == null) {
                logger.debug("Impression.get(" + id + ") returning new instance because hibernate returned null.");
                return new Impression();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Impression", ex);
            return new Impression();
        }
    }

    // Constructors

    /** default constructor */
    public Impression() {
    }


    public boolean canRead(User user){
        Survey survey = Survey.get(surveyid);
        Researcher researcher = Researcher.get(survey.getResearcherid());
        if (user.getUserid()==researcher.getUserid()){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }



    // Property accessors

    public int getImpressionid() {
        return impressionid;
    }

    public void setImpressionid(int impressionid) {
        this.impressionid = impressionid;
    }

    public int getSurveyid() {
        return surveyid;
    }

    public void setSurveyid(int surveyid) {
        this.surveyid = surveyid;
    }
    public String getReferer() {
        return referer;
    }

    public void setReferer(String referer) {
        this.referer = referer;
    }


    public int getQuality() {
        return quality;
    }

    public void setQuality(int quality) {
        this.quality = quality;
    }

    public Date getFirstseen() {
        return firstseen;
    }

    public void setFirstseen(Date firstseen) {
        this.firstseen = firstseen;
    }

    public int getImpressionstotal() {
        return impressionstotal;
    }

    public void setImpressionstotal(int impressionstotal) {
        this.impressionstotal = impressionstotal;
    }


    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    public int getResponseid() {
        return responseid;
    }

    public void setResponseid(int responseid) {
        this.responseid = responseid;
    }

    public int getImpressionstobepaid() {
        return impressionstobepaid;
    }

    public void setImpressionstobepaid(int impressionstobepaid) {
        this.impressionstobepaid=impressionstobepaid;
    }

    public int getImpressionspaid() {
        return impressionspaid;
    }

    public void setImpressionspaid(int impressionspaid) {
        this.impressionspaid=impressionspaid;
    }

    public String getImpressionsbyday() {
        return impressionsbyday;
    }

    public void setImpressionsbyday(String impressionsbyday) {
        this.impressionsbyday=impressionsbyday;
    }
}
