package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.scheduledjobs.CurrentBalanceUpdater;
import com.dneero.session.AuthControlled;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;

import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Incentiveaward extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
    private int incentiveawardid;
    private int userid;
    private int surveyincentiveid;
    private int responseid;
    private boolean isvalid;
    private Date date;
    private String misc1;
    private String misc2;
    private String misc3;
    private String misc4;
    private String misc5;

    public static Incentiveaward get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Incentiveaward");
        try {
            logger.debug("Incentiveaward.get(" + id + ") called.");
            Incentiveaward obj = (Incentiveaward) HibernateUtil.getSession().get(Incentiveaward.class, id);
            if (obj == null) {
                logger.debug("Incentiveaward.get(" + id + ") returning new instance because hibernate returned null.");
                return new Incentiveaward();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Incentiveaward", ex);
            return new Incentiveaward();
        }
    }


    // Constructors

    /** default constructor */
    public Incentiveaward() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getIncentiveawardid() {
        return incentiveawardid;
    }

    public void setIncentiveawardid(int incentiveawardid) {
        this.incentiveawardid=incentiveawardid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public int getSurveyincentiveid() {
        return surveyincentiveid;
    }

    public void setSurveyincentiveid(int surveyincentiveid) {
        this.surveyincentiveid=surveyincentiveid;
    }

    public int getResponseid() {
        return responseid;
    }

    public void setResponseid(int responseid) {
        this.responseid=responseid;
    }

    public boolean getIsvalid() {
        return isvalid;
    }

    public void setIsvalid(boolean isvalid) {
        this.isvalid=isvalid;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date=date;
    }

    public String getMisc1() {
        return misc1;
    }

    public void setMisc1(String misc1) {
        this.misc1=misc1;
    }

    public String getMisc2() {
        return misc2;
    }

    public void setMisc2(String misc2) {
        this.misc2=misc2;
    }

    public String getMisc3() {
        return misc3;
    }

    public void setMisc3(String misc3) {
        this.misc3=misc3;
    }

    public String getMisc4() {
        return misc4;
    }

    public void setMisc4(String misc4) {
        this.misc4=misc4;
    }

    public String getMisc5() {
        return misc5;
    }

    public void setMisc5(String misc5) {
        this.misc5=misc5;
    }
}