package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

/**
 * Blogger generated by hbm2java
 */

public class Invoice extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    public static int STATUS_NOTPAID = 1;
    public static int STATUS_PARTIALLYPAID = 2;
    public static int STATUS_PAID = 3;


    // Fields
     private int invoiceid;
     private int researcherid;
     private Date startdate;
     private Date enddate;
     private int status;
     private double amtbase;
     private double amtdneero;
     private double amtdiscount;
     private double amttotal;
     private double amtpaidtodate;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Invoice get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Invoice");
        try {
            logger.debug("Invoice.get(" + id + ") called.");
            Invoice obj = (Invoice) HibernateUtil.getSession().get(Invoice.class, id);
            if (obj == null) {
                logger.debug("Invoice.get(" + id + ") returning new instance because hibernate returned null.");
                return new Invoice();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Invoice", ex);
            return new Invoice();
        }
    }

    // Constructors

    /** default constructor */
    public Invoice() {
    }


    public boolean canRead(User user){
        if (user.getUserid()==Researcher.get(researcherid).getUserid()){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }



    // Property accessors

    public int getInvoiceid() {
        return invoiceid;
    }

    public void setInvoiceid(int invoiceid) {
        this.invoiceid = invoiceid;
    }

    public int getResearcherid() {
        return researcherid;
    }

    public void setResearcherid(int researcherid) {
        this.researcherid = researcherid;
    }

    public Date getStartdate() {
        return startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEnddate() {
        return enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public double getAmtbase() {
        return amtbase;
    }

    public void setAmtbase(double amtbase) {
        this.amtbase = amtbase;
    }

    public double getAmtdneero() {
        return amtdneero;
    }

    public void setAmtdneero(double amtdneero) {
        this.amtdneero = amtdneero;
    }

    public double getAmtdiscount() {
        return amtdiscount;
    }

    public void setAmtdiscount(double amtdiscount) {
        this.amtdiscount = amtdiscount;
    }

    public double getAmttotal() {
        return amttotal;
    }

    public void setAmttotal(double amttotal) {
        this.amttotal = amttotal;
    }


    public double getAmtpaidtodate() {
        return amtpaidtodate;
    }

    public void setAmtpaidtodate(double amtpaidtodate) {
        this.amtpaidtodate = amtpaidtodate;
    }
}
