package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Invoicetransaction extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields
     private int invoicetransactionid;
     private int invoiceid;
     private Date transactiondate;
     private Double amt;
     private boolean issuccessful;
     private String notes;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Invoicetransaction get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Invoicetransaction");
        try {
            logger.debug("Invoicetransaction.get(" + id + ") called.");
            Invoicetransaction obj = (Invoicetransaction) HibernateUtil.getSession().get(Invoicetransaction.class, id);
            if (obj == null) {
                logger.debug("Invoicetransaction.get(" + id + ") returning new instance because hibernate returned null.");
                return new Invoicetransaction();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Invoicetransaction", ex);
            return new Invoicetransaction();
        }
    }

    // Constructors

    /** default constructor */
    public Invoicetransaction() {
    }


    public boolean canRead(User user){
        Invoice invoice = Invoice.get(invoiceid);
        return invoice.canRead(user);
    }

    public boolean canEdit(User user){
        return canRead(user);
    }



    // Property accessors

    public int getInvoicetransactionid() {
        return invoicetransactionid;
    }

    public void setInvoicetransactionid(int invoicetransactionid) {
        this.invoicetransactionid = invoicetransactionid;
    }

    public int getInvoiceid() {
        return invoiceid;
    }

    public void setInvoiceid(int invoiceid) {
        this.invoiceid = invoiceid;
    }

    public Date getTransactiondate() {
        return transactiondate;
    }

    public void setTransactiondate(Date transactiondate) {
        this.transactiondate = transactiondate;
    }

    public Double getAmt() {
        return amt;
    }

    public void setAmt(Double amt) {
        this.amt = amt;
    }

    public boolean getIssuccessful() {
        return issuccessful;
    }

    public void setIssuccessful(boolean issuccessful) {
        this.issuccessful = issuccessful;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }


}
