package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Iptrack extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int iptrackid;
     private int userid;
     private Date datetime;
     private int activitytypeid;
     private String ip;
     private int octet1;
     private int octet2;
     private int octet3;
     private int octet4;
     private String description;


    public static Iptrack get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Iptrack");
        try {
            logger.debug("Iptrack.get(" + id + ") called.");
            Iptrack obj = (Iptrack) HibernateUtil.getSession().get(Iptrack.class, id);
            if (obj == null) {
                logger.debug("Iptrack.get(" + id + ") returning new instance because hibernate returned null.");
                return new Iptrack();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Iptrack", ex);
            return new Iptrack();
        }
    }


    // Constructors

    /** default constructor */
    public Iptrack() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getIptrackid() {
        return iptrackid;
    }

    public void setIptrackid(int iptrackid) {
        this.iptrackid=iptrackid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public Date getDatetime() {
        return datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime=datetime;
    }

    public int getActivitytypeid() {
        return activitytypeid;
    }

    public void setActivitytypeid(int activitytypeid) {
        this.activitytypeid=activitytypeid;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip=ip;
    }

    public int getOctet1() {
        return octet1;
    }

    public void setOctet1(int octet1) {
        this.octet1=octet1;
    }

    public int getOctet2() {
        return octet2;
    }

    public void setOctet2(int octet2) {
        this.octet2=octet2;
    }

    public int getOctet3() {
        return octet3;
    }

    public void setOctet3(int octet3) {
        this.octet3=octet3;
    }

    public int getOctet4() {
        return octet4;
    }

    public void setOctet4(int octet4) {
        this.octet4=octet4;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description=description;
    }
}