package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.scheduledjobs.CurrentBalanceUpdater;
import com.dneero.session.AuthControlled;
import com.dneero.util.GeneralException;
import com.dneero.htmlui.Pagez;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;

import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Mail extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int mailid;
     private int userid;
     private Date date;
     private boolean isread;
    private boolean isflaggedforcustomercare;
    private String subject;

    public static Mail get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Mail");
        try {
            logger.debug("Mail.get(" + id + ") called.");
            Mail obj = (Mail) HibernateUtil.getSession().get(Mail.class, id);
            if (obj == null) {
                logger.debug("Mail.get(" + id + ") returning new instance because hibernate returned null.");
                return new Mail();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Mail", ex);
            return new Mail();
        }
    }



    // Constructors

    /** default constructor */
    public Mail() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        if (Pagez.getUserSession()!=null && Pagez.getUserSession().getIsCustomerCare()){
            return true;    
        }
        return canRead(user);
    }




    // Property accessors

    public int getMailid() {
        return mailid;
    }

    public void setMailid(int mailid) {
        this.mailid=mailid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date=date;
    }

    public boolean getIsread() {
        return isread;
    }

    public void setIsread(boolean isread) {
        this.isread=isread;
    }

    public boolean getIsflaggedforcustomercare() {
        return isflaggedforcustomercare;
    }

    public void setIsflaggedforcustomercare(boolean isflaggedforcustomercare) {
        this.isflaggedforcustomercare=isflaggedforcustomercare;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject=subject;
    }
}