package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.scheduledjobs.CurrentBalanceUpdater;
import com.dneero.session.AuthControlled;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;

import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Mailchild extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int mailchildid;
     private int mailid;
     private int mailtypeid;
     private Date date;
    private boolean isfromcustomercare;
    private String var1;
    private String var2;
    private String var3;
    private String var4;
    private String var5;


    public static Mailchild get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Mailchild");
        try {
            logger.debug("Mailchild.get(" + id + ") called.");
            Mailchild obj = (Mailchild) HibernateUtil.getSession().get(Mailchild.class, id);
            if (obj == null) {
                logger.debug("Mailchild.get(" + id + ") returning new instance because hibernate returned null.");
                return new Mailchild();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Mailchild", ex);
            return new Mailchild();
        }
    }



    // Constructors

    /** default constructor */
    public Mailchild() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getMailchildid() {
        return mailchildid;
    }

    public void setMailchildid(int mailchildid) {
        this.mailchildid=mailchildid;
    }

    public int getMailid() {
        return mailid;
    }

    public void setMailid(int mailid) {
        this.mailid=mailid;
    }

    public int getMailtypeid() {
        return mailtypeid;
    }

    public void setMailtypeid(int mailtypeid) {
        this.mailtypeid=mailtypeid;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date=date;
    }

    public boolean getIsfromcustomercare() {
        return isfromcustomercare;
    }

    public void setIsfromcustomercare(boolean isfromcustomercare) {
        this.isfromcustomercare=isfromcustomercare;
    }

    public String getVar1() {
        return var1;
    }

    public void setVar1(String var1) {
        this.var1=var1;
    }

    public String getVar2() {
        return var2;
    }

    public void setVar2(String var2) {
        this.var2=var2;
    }

    public String getVar3() {
        return var3;
    }

    public void setVar3(String var3) {
        this.var3=var3;
    }

    public String getVar4() {
        return var4;
    }

    public void setVar4(String var4) {
        this.var4=var4;
    }

    public String getVar5() {
        return var5;
    }

    public void setVar5(String var5) {
        this.var5=var5;
    }
}