package com.dneero.dao;

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:25 PM by Hibernate Tools 3.1.0.beta4



/**
 * Marketeraddress generated by hbm2java
 */

public class Marketeraddress extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields    

     private int marketeraddressid;
     private int marketerid;
     private int addressid;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Marketeraddress get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Marketeraddress");
        try {
            logger.debug("Marketeraddress.get(" + id + ") called.");
            Marketeraddress obj = (Marketeraddress) HibernateUtil.getSession().get(Marketeraddress.class, id);
            if (obj == null) {
                logger.debug("Marketeraddress.get(" + id + ") returning new instance because hibernate returned null.");
                return new Marketeraddress();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Marketeraddress", ex);
            return new Marketeraddress();
        }
    }

    // Constructors

    /** default constructor */
    public Marketeraddress() {
    }

    
    /** full constructor */
    public Marketeraddress(int marketeraddressid, int marketerid, int addressid) {
        this.marketeraddressid = marketeraddressid;
        this.marketerid = marketerid;
        this.addressid = addressid;
    }
    

   
    // Property accessors

    public int getMarketeraddressid() {
        return this.marketeraddressid;
    }
    
    public void setMarketeraddressid(int marketeraddressid) {
        this.marketeraddressid = marketeraddressid;
    }

    public int getMarketerid() {
        return this.marketerid;
    }
    
    public void setMarketerid(int marketerid) {
        this.marketerid = marketerid;
    }

    public int getAddressid() {
        return this.addressid;
    }
    
    public void setAddressid(int addressid) {
        this.addressid = addressid;
    }
   








}
