package com.dneero.dao;

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:22 PM by Hibernate Tools 3.1.0.beta4



/**
 * Marketer generated by hbm2java
 */

public class Marketer extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields    

     private int marketerid;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Marketer get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Marketer");
        try {
            logger.debug("Marketer.get(" + id + ") called.");
            Marketer obj = (Marketer) HibernateUtil.getSession().get(Marketer.class, id);
            if (obj == null) {
                logger.debug("Marketer.get(" + id + ") returning new instance because hibernate returned null.");
                return new Marketer();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Marketer", ex);
            return new Marketer();
        }
    }

    // Constructors

    /** default constructor */
    public Marketer() {
    }

    
    /** full constructor */
    public Marketer(int marketerid) {
        this.marketerid = marketerid;
    }
    

   
    // Property accessors

    public int getMarketerid() {
        return this.marketerid;
    }
    
    public void setMarketerid(int marketerid) {
        this.marketerid = marketerid;
    }
   








}
