package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Offer generated by hbm2java
 */

public class Offercriteriagender extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int offercriteriagenderid;
     private int offercriteriaid;
     //Value of ethnicity drawn from com.dneero.Blogger
     private int gender;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Offercriteriagender get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Offercriteriaeducationlevel");
        try {
            logger.debug("Offercriteriagender.get(" + id + ") called.");
            Offercriteriagender obj = (Offercriteriagender) HibernateUtil.getSession().get(Offercriteriagender.class, id);
            if (obj == null) {
                logger.debug("Offercriteriagender.get(" + id + ") returning new instance because hibernate returned null.");
                return new Offercriteriagender();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Offercriteriagender", ex);
            return new Offercriteriagender();
        }
    }

    // Constructors

    /** default constructor */
    public Offercriteriagender() {
    }




    // Property accessors

    public int getOffercriteriagenderid() {
        return offercriteriagenderid;
    }

    public void setOffercriteriagenderid(int offercriteriagenderid) {
        this.offercriteriagenderid = offercriteriagenderid;
    }

    public int getOffercriteriaid() {
        return offercriteriaid;
    }

    public void setOffercriteriaid(int offercriteriaid) {
        this.offercriteriaid = offercriteriaid;
    }

    public int getGender() {
        return gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }


}
