package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Offer generated by hbm2java
 */

public class Offercriteriamaritalstatus extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int offercriteriamaritalstatusid;
     private int offercriteriaid;
     //Value drawn from com.dneero.Blogger
     private int maritalstatus;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Offercriteriamaritalstatus get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Offercriteriamaritalstatus");
        try {
            logger.debug("Offercriteriamaritalstatus.get(" + id + ") called.");
            Offercriteriamaritalstatus obj = (Offercriteriamaritalstatus) HibernateUtil.getSession().get(Offercriteriamaritalstatus.class, id);
            if (obj == null) {
                logger.debug("Offercriteriamaritalstatus.get(" + id + ") returning new instance because hibernate returned null.");
                return new Offercriteriamaritalstatus();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Offercriteriamaritalstatus", ex);
            return new Offercriteriamaritalstatus();
        }
    }

    // Constructors

    /** default constructor */
    public Offercriteriamaritalstatus() {
    }




    // Property accessors

    public int getOffercriteriamaritalstatusid() {
        return offercriteriamaritalstatusid;
    }

    public void setOffercriteriamaritalstatusid(int offercriteriamaritalstatusid) {
        this.offercriteriamaritalstatusid = offercriteriamaritalstatusid;
    }

    public int getOffercriteriaid() {
        return offercriteriaid;
    }

    public void setOffercriteriaid(int offercriteriaid) {
        this.offercriteriaid = offercriteriaid;
    }

    public int getMaritalstatus() {
        return maritalstatus;
    }

    public void setMaritalstatus(int maritalstatus) {
        this.maritalstatus = maritalstatus;
    }


}
