package com.dneero.dao;
// Generated Apr 17, 2006 3:45:24 PM by Hibernate Tools 3.1.0.beta4

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

import org.apache.log4j.Logger;


/**
 * Offer generated by hbm2java
 */

public class Offer extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields    

     private int offerid;
     private String title;
     private String description;
     private double willingtopayperrespondent;
     private int numberofrespondentsrequested;
     private Date startdate;
     private Date enddate;

     private Set<Offercriteria> offercriteria = new HashSet<Offercriteria>();

    public Set<Offercriteria> getOffercriteria() {
        return offercriteria;
    }

    public void setOffercriteria(Set<Offercriteria> offercriteria) {
        this.offercriteria = offercriteria;
    }


    //Validator
    public void validateRegerEntity() throws GeneralException {
      
    }

    //Loader
    public void load(){

    }

    public static Offer get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Offer");
        try {
            logger.debug("Offer.get(" + id + ") called.");
            Offer obj = (Offer) HibernateUtil.getSession().get(Offer.class, id);
            if (obj == null) {
                logger.debug("Offer.get(" + id + ") returning new instance because hibernate returned null.");
                return new Offer();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Offer", ex);
            return new Offer();
        }
    }

    // Constructors

    /** default constructor */
    public Offer() {
    }

    /** minimal constructor */
    public Offer(int offerid, String title, double willingtopayperrespondent, int numberofrespondentsrequested, Date startdate, Date enddate) {
        this.offerid = offerid;
        this.title = title;
        this.willingtopayperrespondent = willingtopayperrespondent;
        this.numberofrespondentsrequested = numberofrespondentsrequested;
        this.startdate = startdate;
        this.enddate = enddate;
    }

    /** full constructor */
    public Offer(int offerid, String title, String description, double willingtopayperrespondent, int numberofrespondentsrequested, Date startdate, Date enddate) {
        this.offerid = offerid;
        this.title = title;
        this.description = description;
        this.willingtopayperrespondent = willingtopayperrespondent;
        this.numberofrespondentsrequested = numberofrespondentsrequested;
        this.startdate = startdate;
        this.enddate = enddate;
    }



    // Property accessors

    public int getOfferid() {
        return this.offerid;
    }

    public void setOfferid(int offerid) {
        this.offerid = offerid;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public double getWillingtopayperrespondent() {
        return this.willingtopayperrespondent;
    }

    public void setWillingtopayperrespondent(double willingtopayperrespondent) {
        this.willingtopayperrespondent = willingtopayperrespondent;
    }

    public int getNumberofrespondentsrequested() {
        return this.numberofrespondentsrequested;
    }

    public void setNumberofrespondentsrequested(int numberofrespondentsrequested) {
        this.numberofrespondentsrequested = numberofrespondentsrequested;
    }

    public Date getStartdate() {
        return this.startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEnddate() {
        return this.enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }





}
