package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Offer generated by hbm2java
 */

public class Offercriteriaeducationlevel extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int offercriteriaeducationlevelid;
     private int offercriteriaid;
     //Value of ethnicity drawn from com.dneero.Blogger
     private int educationlevel;




    //Validator
    public void validateRegerEntity() throws GeneralException {
        
    }

    //Loader
    public void load(){

    }

    public static Offercriteriaeducationlevel get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Offercriteriaeducationlevel");
        try {
            logger.debug("Offercriteriaeducationlevel.get(" + id + ") called.");
            Offercriteriaeducationlevel obj = (Offercriteriaeducationlevel) HibernateUtil.getSession().get(Offercriteriaeducationlevel.class, id);
            if (obj == null) {
                logger.debug("Offercriteriaeducationlevel.get(" + id + ") returning new instance because hibernate returned null.");
                return new Offercriteriaeducationlevel();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Offercriteriaeducationlevel", ex);
            return new Offercriteriaeducationlevel();
        }
    }

    // Constructors

    /** default constructor */
    public Offercriteriaeducationlevel() {
    }




    // Property accessors

    public int getOffercriteriaeducationlevelid() {
        return offercriteriaeducationlevelid;
    }

    public void setOffercriteriaeducationlevelid(int offercriteriaeducationlevelid) {
        this.offercriteriaeducationlevelid = offercriteriaeducationlevelid;
    }

    public int getOffercriteriaid() {
        return offercriteriaid;
    }

    public void setOffercriteriaid(int offercriteriaid) {
        this.offercriteriaid = offercriteriaid;
    }

    public int getEducationlevel() {
        return educationlevel;
    }

    public void setEducationlevel(int educationlevel) {
        this.educationlevel = educationlevel;
    }


}
