package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;

import java.util.Set;
import java.util.HashSet;
import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Panel extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int panelid;
     private int researcherid;
     private String name;
     private Date createdate;
     
     private Set<Panelmembership> panelmemberships = new HashSet<Panelmembership>();


    public static Panel get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Panel");
        try {
            logger.debug("Panel.get(" + id + ") called.");
            Panel obj = (Panel) HibernateUtil.getSession().get(Panel.class, id);
            if (obj == null) {
                logger.debug("Panel.get(" + id + ") returning new instance because hibernate returned null.");
                return new Panel();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Panel", ex);
            return new Panel();
        }
    }

    // Constructors

    /** default constructor */
    public Panel() {
    }

    public boolean canRead(User user){
        return canEdit(user);
    }

    public boolean canEdit(User user){
        if (user.getResearcherid()==researcherid){
            return true;
        }
        return false;
    }




    // Property accessors


    public int getPanelid() {
        return panelid;
    }

    public void setPanelid(int panelid) {
        this.panelid = panelid;
    }

    public int getResearcherid() {
        return researcherid;
    }

    public void setResearcherid(int researcherid) {
        this.researcherid = researcherid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }


    public Set<Panelmembership> getPanelmemberships() {
        return panelmemberships;
    }

    public void setPanelmemberships(Set<Panelmembership> panelmemberships) {
        this.panelmemberships = panelmemberships;
    }
}
