package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Questionresponse extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int questionresponseid;
     private int questionid;
     private int responseid;
     private int bloggerid;
     private String name;
     private String value;
     private Response response;




    public static Questionresponse get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Questionresponse");
        try {
            logger.debug("Questionresponse.get(" + id + ") called.");
            Questionresponse obj = (Questionresponse) HibernateUtil.getSession().get(Questionresponse.class, id);
            if (obj == null) {
                logger.debug("Questionresponse.get(" + id + ") returning new instance because hibernate returned null.");
                return new Questionresponse();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Questionresponse", ex);
            return new Questionresponse();
        }
    }

    // Constructors

    /** default constructor */
    public Questionresponse() {
    }


    public boolean canRead(User user){
        Question question = Question.get(questionid);
        return question.canRead(user);
    }

    public boolean canEdit(User user){
        return canRead(user);
    }



    // Property accessors

    public int getQuestionresponseid() {
        return questionresponseid;
    }

    public void setQuestionresponseid(int questionresponseid) {
        this.questionresponseid = questionresponseid;
    }

    public int getQuestionid() {
        return questionid;
    }

    public void setQuestionid(int questionid) {
        this.questionid = questionid;
    }

    public int getBloggerid() {
        return bloggerid;
    }

    public void setBloggerid(int bloggerid) {
        this.bloggerid = bloggerid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public int getResponseid() {
        return responseid;
    }

    public void setResponseid(int responseid) {
        this.responseid = responseid;
    }

    public Response getResponse() {
        return response;
    }

    public void setResponse(Response response) {
        this.response=response;
    }
}
