package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Rank extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int rankid;
     private int userid;
     private String name;

    public static Rank get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Rank");
        try {
            logger.debug("Rank.get(" + id + ") called.");
            Rank obj = (Rank) HibernateUtil.getSession().get(Rank.class, id);
            if (obj == null) {
                logger.debug("Rank.get(" + id + ") returning new instance because hibernate returned null.");
                return new Rank();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Rank", ex);
            return new Rank();
        }
    }

    // Constructors

    /** default constructor */
    public Rank() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getRankid() {
        return rankid;
    }

    public void setRankid(int rankid) {
        this.rankid = rankid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}