package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Rankquestion extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int rankquestionid;
     private int rankid;
     private int questionid;
     private String answer;
     private int points;
     private String opt1;
     private String opt2;

    public static Rankquestion get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Rankquestion");
        try {
            logger.debug("Rankquestion.get(" + id + ") called.");
            Rankquestion obj = (Rankquestion) HibernateUtil.getSession().get(Rankquestion.class, id);
            if (obj == null) {
                logger.debug("Rankquestion.get(" + id + ") returning new instance because hibernate returned null.");
                return new Rankquestion();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Rankquestion", ex);
            return new Rankquestion();
        }
    }

    // Constructors

    /** default constructor */
    public Rankquestion() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getRankquestionid() {
        return rankquestionid;
    }

    public void setRankquestionid(int rankquestionid) {
        this.rankquestionid = rankquestionid;
    }

    public int getRankid() {
        return rankid;
    }

    public void setRankid(int rankid) {
        this.rankid = rankid;
    }

    public int getQuestionid() {
        return questionid;
    }

    public void setQuestionid(int questionid) {
        this.questionid = questionid;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public int getPoints() {
        return points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public String getOpt1() {
        return opt1;
    }

    public void setOpt1(String opt1) {
        this.opt1 = opt1;
    }

    public String getOpt2() {
        return opt2;
    }

    public void setOpt2(String opt2) {
        this.opt2 = opt2;
    }
}