package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Marketer generated by hbm2java
 */

public class Researcherbilling extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int researcherbillingid;
     private int researcherid;
     private String billingname;
     private String billingaddress1;
     private String billingaddress2;
     private String billingcity;
     private String billingstate;
     private String billingzip;
     private int billingpaymentmethod;
     private String ccnum;
     private int ccexpmonth;
     private int ccexpyear;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Researcherbilling get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Researcherbilling");
        try {
            logger.debug("Researcherbilling.get(" + id + ") called.");
            Researcherbilling obj = (Researcherbilling) HibernateUtil.getSession().get(Researcherbilling.class, id);
            if (obj == null) {
                logger.debug("Researcherbilling.get(" + id + ") returning new instance because hibernate returned null.");
                return new Researcherbilling();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Researcher", ex);
            return new Researcherbilling();
        }
    }

    // Constructors

    /** default constructor */
    public Researcherbilling() {
    }


    /** full constructor */
    public Researcherbilling(int researcherbillingid) {
        this.researcherbillingid = researcherbillingid;
    }



    // Property accessors

    public int getResearcherbillingid() {
        return researcherbillingid;
    }

    public void setResearcherbillingid(int researcherbillingid) {
        this.researcherbillingid = researcherbillingid;
    }

    public int getResearcherid() {
        return researcherid;
    }

    public void setResearcherid(int researcherid) {
        this.researcherid = researcherid;
    }

    public String getBillingname() {
        return billingname;
    }

    public void setBillingname(String billingname) {
        this.billingname = billingname;
    }

    public String getBillingaddress1() {
        return billingaddress1;
    }

    public void setBillingaddress1(String billingaddress1) {
        this.billingaddress1 = billingaddress1;
    }

    public String getBillingaddress2() {
        return billingaddress2;
    }

    public void setBillingaddress2(String billingaddress2) {
        this.billingaddress2 = billingaddress2;
    }

    public String getBillingcity() {
        return billingcity;
    }

    public void setBillingcity(String billingcity) {
        this.billingcity = billingcity;
    }

    public String getBillingstate() {
        return billingstate;
    }

    public void setBillingstate(String billingstate) {
        this.billingstate = billingstate;
    }

    public String getBillingzip() {
        return billingzip;
    }

    public void setBillingzip(String billingzip) {
        this.billingzip = billingzip;
    }

    public int getBillingpaymentmethod() {
        return billingpaymentmethod;
    }

    public void setBillingpaymentmethod(int billingpaymentmethod) {
        this.billingpaymentmethod = billingpaymentmethod;
    }

    public String getCcnum() {
        return ccnum;
    }

    public void setCcnum(String ccnum) {
        this.ccnum = ccnum;
    }

    public int getCcexpmonth() {
        return ccexpmonth;
    }

    public void setCcexpmonth(int ccexpmonth) {
        this.ccexpmonth = ccexpmonth;
    }

    public int getCcexpyear() {
        return ccexpyear;
    }

    public void setCcexpyear(int ccexpyear) {
        this.ccexpyear = ccexpyear;
    }


}
