package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

import java.util.Set;
import java.util.HashSet;
// Generated Apr 17, 2006 3:45:22 PM by Hibernate Tools 3.1.0.beta4



/**
 * Marketer generated by hbm2java
 */

public class Researcher extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields    

     private int researcherid;
     private int userid;
     private String companyname;
     private String companytype;
     private String phone;

     private Set<Emailinvitebatch> emailinvitebatches = new HashSet<Emailinvitebatch>();
    private Set<Panel> panels = new HashSet<Panel>();



    public static Researcher get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Researcher");
        try {
            logger.debug("Researcher.get(" + id + ") called.");
            Researcher obj = (Researcher) HibernateUtil.getSession().get(Researcher.class, id);
            if (obj == null) {
                logger.debug("Researcher.get(" + id + ") returning new instance because hibernate returned null.");
                return new Researcher();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Researcher", ex);
            return new Researcher();
        }
    }

    // Constructors

    /** default constructor */
    public Researcher() {
    }


    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }


    
    /** full constructor */
    public Researcher(int researcherid) {
        this.researcherid = researcherid;
    }
    

   
    // Property accessors

    public int getResearcherid() {
        return this.researcherid;
    }
    
    public void setResearcherid(int researcherid) {
        this.researcherid = researcherid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }



    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getCompanytype() {
        return companytype;
    }

    public void setCompanytype(String companytype) {
        this.companytype = companytype;
    }

    public String getCompanyname() {
        return companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }


    public Set<Emailinvitebatch> getEmailinvitebatches() {
        return emailinvitebatches;
    }

    public void setEmailinvitebatches(Set<Emailinvitebatch> emailinvitebatches) {
        this.emailinvitebatches = emailinvitebatches;
    }

    public Set<Panel> getPanels() {
        return panels;
    }

    public void setPanels(Set<Panel> panels) {
        this.panels = panels;
    }
}
