package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import com.dneero.incentive.Incentive;
import com.dneero.incentive.IncentiveFactory;
import org.apache.log4j.Logger;

import java.util.Date;
import java.util.Iterator;

/**
 * Blogger generated by hbm2java
 */

public class Response extends BasePersistentClass implements java.io.Serializable, AuthControlled {

    public static int POSTATUS_NOTPOSTED = 0;
    public static int POSTATUS_POSTEDATLEASTONCE = 1;
    public static int POSTATUS_POSTED = 2;
    public static int POSTATUS_NOTPOSTEDTIMELIMITPASSED = 3;

    // Fields
     private int responseid;
     private int surveyid;
     private int bloggerid;
     private Date responsedate;
     private Survey survey;
     private int referredbyuserid;
     private boolean isforcharity;
     private String charityname;
     private int poststatus;
     private boolean ispaid;
     private String responsestatushtml;
     private boolean isresearcherreviewed;
     private boolean issysadminreviewed;
     private boolean isresearcherrejected;
     private boolean issysadminrejected;
     private int surveyincentiveid;
     private int impressionstotal;
     private int impressionstobepaid;
     private int impressionspaid;
     private boolean isdatamigrated;
     private String impressionsbyday;
     private Surveyincentive surveyincentive;


    public static Response get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Response");
        try {
            logger.debug("Response.get(" + id + ") called.");
            Response obj = (Response) HibernateUtil.getSession().get(Response.class, id);
            if (obj == null) {
                logger.debug("Response.get(" + id + ") returning new instance because hibernate returned null.");
                return new Response();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Response", ex);
            return new Response();
        }
    }

    // Constructors

    /** default constructor */
    public Response() {
    }


    public boolean canRead(User user){
        Survey survey = Survey.get(surveyid);
        if (user.getUserid()==Researcher.get(survey.getResearcherid()).getUserid()){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }

    public Incentive getIncentive(){
        Incentive incentiveOut = null;
        if (getSurveyincentive()!=null && getSurveyincentive().getSurveyincentiveid()>0){
            incentiveOut = IncentiveFactory.getById(getSurveyincentive().getType(), getSurveyincentive());
        }
        if (incentiveOut==null){
            incentiveOut =IncentiveFactory.getDefaultIncentive();
        }
        return incentiveOut;
    }



    // Property accessors

    public int getResponseid() {
        return responseid;
    }

    public void setResponseid(int responseid) {
        this.responseid = responseid;
    }

    public int getSurveyid() {
        return surveyid;
    }

    public void setSurveyid(int surveyid) {
        this.surveyid = surveyid;
    }

    public int getBloggerid() {
        return bloggerid;
    }

    public void setBloggerid(int bloggerid) {
        this.bloggerid = bloggerid;
    }

    public Date getResponsedate() {
        return responsedate;
    }

    public void setResponsedate(Date responsedate) {
        this.responsedate = responsedate;
    }

    public Survey getSurvey() {
        return survey;
    }

    public void setSurvey(Survey survey) {
        this.survey = survey;
    }

    public int getReferredbyuserid() {
        return referredbyuserid;
    }

    public void setReferredbyuserid(int referredbyuserid) {
        this.referredbyuserid = referredbyuserid;
    }

    public boolean getIsforcharity() {
        return isforcharity;
    }

    public void setIsforcharity(boolean isforcharity) {
        this.isforcharity = isforcharity;
    }

    public String getCharityname() {
        return charityname;
    }

    public void setCharityname(String charityname) {
        this.charityname = charityname;
    }

    public int getPoststatus() {
        return poststatus;
    }

    public void setPoststatus(int poststatus) {
        this.poststatus = poststatus;
    }

    public boolean getIspaid() {
        return ispaid;
    }

    public void setIspaid(boolean ispaid) {
        this.ispaid = ispaid;
    }


    public String getResponsestatushtml() {
        return responsestatushtml;
    }

    public void setResponsestatushtml(String responsestatushtml) {
        this.responsestatushtml = responsestatushtml;
    }

    public boolean getIssysadminrejected() {
        return issysadminrejected;
    }

    public void setIssysadminrejected(boolean issysadminrejected) {
        this.issysadminrejected=issysadminrejected;
    }

    public boolean getIsresearcherreviewed() {
        return isresearcherreviewed;
    }

    public void setIsresearcherreviewed(boolean isresearcherreviewed) {
        this.isresearcherreviewed=isresearcherreviewed;
    }

    public boolean getIssysadminreviewed() {
        return issysadminreviewed;
    }

    public void setIssysadminreviewed(boolean issysadminreviewed) {
        this.issysadminreviewed=issysadminreviewed;
    }

    public boolean getIsresearcherrejected() {
        return isresearcherrejected;
    }

    public void setIsresearcherrejected(boolean isresearcherrejected) {
        this.isresearcherrejected=isresearcherrejected;
    }

    public int getSurveyincentiveid() {
        return surveyincentiveid;
    }

    public void setSurveyincentiveid(int surveyincentiveid) {
        this.surveyincentiveid=surveyincentiveid;
    }

    public Surveyincentive getSurveyincentive() {
        return surveyincentive;
    }

    public void setSurveyincentive(Surveyincentive surveyincentive) {
        this.surveyincentive=surveyincentive;
    }

    public String getImpressionsbyday() {
        return impressionsbyday;
    }

    public void setImpressionsbyday(String impressionsbyday) {
        this.impressionsbyday=impressionsbyday;
    }

    public int getImpressionstotal() {
        return impressionstotal;
    }

    public void setImpressionstotal(int impressionstotal) {
        this.impressionstotal=impressionstotal;
    }

    public int getImpressionstobepaid() {
        return impressionstobepaid;
    }

    public void setImpressionstobepaid(int impressionstobepaid) {
        this.impressionstobepaid=impressionstobepaid;
    }

    public int getImpressionspaid() {
        return impressionspaid;
    }

    public void setImpressionspaid(int impressionspaid) {
        this.impressionspaid=impressionspaid;
    }

    public boolean getIsdatamigrated() {
        return isdatamigrated;
    }

    public void setIsdatamigrated(boolean isdatamigrated) {
        this.isdatamigrated=isdatamigrated;
    }
}
