package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Respondentfilter extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int respondentfilterid;
     private int userid;
     private String name;
     private String criteriaxml;


    public static Respondentfilter get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Respondentfilter");
        try {
            logger.debug("Respondentfilter.get(" + id + ") called.");
            Respondentfilter obj = (Respondentfilter) HibernateUtil.getSession().get(Respondentfilter.class, id);
            if (obj == null) {
                logger.debug("Respondentfilter.get(" + id + ") returning new instance because hibernate returned null.");
                return new Respondentfilter();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Respondentfilter", ex);
            return new Respondentfilter();
        }
    }

    // Constructors

    /** default constructor */
    public Respondentfilter() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }

    public int getRespondentfilterid() {
        return respondentfilterid;
    }

    public void setRespondentfilterid(int respondentfilterid) {
        this.respondentfilterid = respondentfilterid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCriteriaxml() {
        return criteriaxml;
    }

    public void setCriteriaxml(String criteriaxml) {
        this.criteriaxml = criteriaxml;
    }
}