package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Revenue extends BasePersistentClass implements java.io.Serializable, RegerEntity {



    // Fields
     private int revenueid;
     private int invoiceid;
     private Date revenuedate;
     private double amt;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Revenue get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Revenue");
        try {
            logger.debug("Revenue.get(" + id + ") called.");
            Revenue obj = (Revenue) HibernateUtil.getSession().get(Revenue.class, id);
            if (obj == null) {
                logger.debug("Revenue.get(" + id + ") returning new instance because hibernate returned null.");
                return new Revenue();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Revenue", ex);
            return new Revenue();
        }
    }

    // Constructors

    /** default constructor */
    public Revenue() {
    }






    // Property accessors

    public int getRevenueid() {
        return revenueid;
    }

    public void setRevenueid(int revenueid) {
        this.revenueid = revenueid;
    }

    public int getInvoiceid() {
        return invoiceid;
    }

    public void setInvoiceid(int invoiceid) {
        this.invoiceid = invoiceid;
    }

    public Date getRevenuedate() {
        return revenuedate;
    }

    public void setRevenuedate(Date revenuedate) {
        this.revenuedate = revenuedate;
    }

    public double getAmt() {
        return amt;
    }

    public void setAmt(double amt) {
        this.amt = amt;
    }


}
