package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;

import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Review extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
    private int reviewid;
    private Date dateofcreation;
    private Date datelastupdated;
    private int type;
    private int id;
    private String researchernotes;
    private String sysadminnotes;
    private boolean issysadminreviewed;
    private boolean isresearcherreviewed;
    private boolean isresearcherrejected;
    private boolean issysadminrejected;
    private boolean isresearcherwarned;
    private boolean issysadminwarned;
    private int useridofcontentcreator;
    private int useridofresearcher;



    public static Review get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Review");
        try {
            logger.debug("Review.get(" + id + ") called.");
            Review obj = (Review) HibernateUtil.getSession().get(Review.class, id);
            if (obj == null) {
                logger.debug("Review.get(" + id + ") returning new instance because hibernate returned null.");
                return new Review();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Review", ex);
            return new Review();
        }
    }

    // Constructors

    /** default constructor */
    public Review() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getReviewid() {
        return reviewid;
    }

    public void setReviewid(int reviewid) {
        this.reviewid=reviewid;
    }

    public Date getDateofcreation() {
        return dateofcreation;
    }

    public void setDateofcreation(Date dateofcreation) {
        this.dateofcreation=dateofcreation;
    }

    public Date getDatelastupdated() {
        return datelastupdated;
    }

    public void setDatelastupdated(Date datelastupdated) {
        this.datelastupdated=datelastupdated;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type=type;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id=id;
    }

    public boolean getIssysadminreviewed() {
        return issysadminreviewed;
    }

    public void setIssysadminreviewed(boolean issysadminreviewed) {
        this.issysadminreviewed=issysadminreviewed;
    }

    public boolean getIsresearcherreviewed() {
        return isresearcherreviewed;
    }

    public void setIsresearcherreviewed(boolean isresearcherreviewed) {
        this.isresearcherreviewed=isresearcherreviewed;
    }



    public int getUseridofcontentcreator() {
        return useridofcontentcreator;
    }

    public void setUseridofcontentcreator(int useridofcontentcreator) {
        this.useridofcontentcreator=useridofcontentcreator;
    }

    public int getUseridofresearcher() {
        return useridofresearcher;
    }

    public void setUseridofresearcher(int useridofresearcher) {
        this.useridofresearcher=useridofresearcher;
    }

    public String getResearchernotes() {
        return researchernotes;
    }

    public void setResearchernotes(String researchernotes) {
        this.researchernotes=researchernotes;
    }

    public String getSysadminnotes() {
        return sysadminnotes;
    }

    public void setSysadminnotes(String sysadminnotes) {
        this.sysadminnotes=sysadminnotes;
    }

    public boolean getIsresearcherrejected() {
        return isresearcherrejected;
    }

    public void setIsresearcherrejected(boolean isresearcherrejected) {
        this.isresearcherrejected=isresearcherrejected;
    }

    public boolean getIssysadminrejected() {
        return issysadminrejected;
    }

    public void setIssysadminrejected(boolean issysadminrejected) {
        this.issysadminrejected=issysadminrejected;
    }

    public boolean getIsresearcherwarned() {
        return isresearcherwarned;
    }

    public void setIsresearcherwarned(boolean isresearcherwarned) {
        this.isresearcherwarned=isresearcherwarned;
    }

    public boolean getIssysadminwarned() {
        return issysadminwarned;
    }

    public void setIssysadminwarned(boolean issysadminwarned) {
        this.issysadminwarned=issysadminwarned;
    }
}