package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.scheduledjobs.CurrentBalanceUpdater;
import com.dneero.session.AuthControlled;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;

import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Schedextime extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
     private int schedextimeid;
    private Date date;
    private String taskname;
    private String servername;
    private int millistoexecute;


    public static Schedextime get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Schedextime");
        try {
            logger.debug("Schedextime.get(" + id + ") called.");
            Schedextime obj = (Schedextime) HibernateUtil.getSession().get(Schedextime.class, id);
            if (obj == null) {
                logger.debug("Schedextime.get(" + id + ") returning new instance because hibernate returned null.");
                return new Schedextime();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Schedextime", ex);
            return new Schedextime();
        }
    }




    // Constructors

    /** default constructor */
    public Schedextime() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getSchedextimeid() {
        return schedextimeid;
    }

    public void setSchedextimeid(int schedextimeid) {
        this.schedextimeid=schedextimeid;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date=date;
    }

    public String getTaskname() {
        return taskname;
    }

    public void setTaskname(String taskname) {
        this.taskname=taskname;
    }

    public String getServername() {
        return servername;
    }

    public void setServername(String servername) {
        this.servername=servername;
    }

    public int getMillistoexecute() {
        return millistoexecute;
    }

    public void setMillistoexecute(int millistoexecute) {
        this.millistoexecute=millistoexecute;
    }
}