package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;

import java.util.Set;
import java.util.HashSet;
import java.util.Date;

import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Supportissuecomm extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields
     private int supportissuecommid;
     private int supportissueid;
     private Date datetime;
     private boolean isfromdneeroadmin;
     private String notes;

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Supportissuecomm get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Supportissuecomm");
        try {
            logger.debug("Supportissuecomm.get(" + id + ") called.");
            Supportissuecomm obj = (Supportissuecomm) HibernateUtil.getSession().get(Supportissuecomm.class, id);
            if (obj == null) {
                logger.debug("Supportissuecomm.get(" + id + ") returning new instance because hibernate returned null.");
                return new Supportissuecomm();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Supportissuecomm", ex);
            return new Supportissuecomm();
        }
    }

    // Constructors

    /** default constructor */
    public Supportissuecomm() {
    }






    // Property accessors

    public int getSupportissuecommid() {
        return supportissuecommid;
    }

    public void setSupportissuecommid(int supportissuecommid) {
        this.supportissuecommid = supportissuecommid;
    }

    public int getSupportissueid() {
        return supportissueid;
    }

    public void setSupportissueid(int supportissueid) {
        this.supportissueid = supportissueid;
    }

    public Date getDatetime() {
        return datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public boolean isIsfromdneeroadmin() {
        return isfromdneeroadmin;
    }

    public void setIsfromdneeroadmin(boolean isfromdneeroadmin) {
        this.isfromdneeroadmin = isfromdneeroadmin;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

}
