package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Surveycriteriapolitics extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int surveycriteriapoliticsid;
     private int surveycriteriaid;
     private int politics;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Surveycriteriapolitics get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Surveycriteriapolitics");
        try {
            logger.debug("Surveycriteriapolitics.get(" + id + ") called.");
            Surveycriteriapolitics obj = (Surveycriteriapolitics) HibernateUtil.getSession().get(Surveycriteriapolitics.class, id);
            if (obj == null) {
                logger.debug("Surveycriteriapolitics.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveycriteriapolitics();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveycriteriapolitics", ex);
            return new Surveycriteriapolitics();
        }
    }

    // Constructors

    /** default constructor */
    public Surveycriteriapolitics() {
    }




    // Property accessors

    public int getSurveycriteriapoliticsid() {
        return surveycriteriapoliticsid;
    }

    public void setSurveycriteriapoliticsid(int surveycriteriapoliticsid) {
        this.surveycriteriapoliticsid = surveycriteriapoliticsid;
    }

    public int getSurveycriteriaid() {
        return surveycriteriaid;
    }

    public void setSurveycriteriaid(int surveycriteriaid) {
        this.surveycriteriaid = surveycriteriaid;
    }

    public int getPolitics() {
        return politics;
    }

    public void setPolitics(int politics) {
        this.politics = politics;
    }


}
