package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;

import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Surveycriteriaethnicity extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int surveycriteriaethnicityid;
     private int surveycriteriaid;
     //Value of ethnicity drawn from com.dneero.Blogger
     private int ethnicity;




    //Validator
    public void validateRegerEntity() throws GeneralException {
    
    }

    //Loader
    public void load(){

    }

    public static Surveycriteriaethnicity get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Surveycriteriaethnicity");
        try {
            logger.debug("Surveycriteriaethnicity.get(" + id + ") called.");
            Surveycriteriaethnicity obj = (Surveycriteriaethnicity) HibernateUtil.getSession().get(Surveycriteriaethnicity.class, id);
            if (obj == null) {
                logger.debug("Surveycriteriaethnicity.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveycriteriaethnicity();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveycriteriaethnicity", ex);
            return new Surveycriteriaethnicity();
        }
    }

    // Constructors

    /** default constructor */
    public Surveycriteriaethnicity() {
    }




    // Property accessors

    public int getSurveycriteriaethnicityid() {
        return surveycriteriaethnicityid;
    }

    public void setSurveycriteriaethnicityid(int surveycriteriaethnicityid) {
        this.surveycriteriaethnicityid = surveycriteriaethnicityid;
    }

    public int getSurveycriteriaid() {
        return surveycriteriaid;
    }

    public void setSurveycriteriaid(int surveycriteriaid) {
        this.surveycriteriaid = surveycriteriaid;
    }

    public int getEthnicity() {
        return ethnicity;
    }

    public void setEthnicity(int ethnicity) {
        this.ethnicity = ethnicity;
    }


}
