package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Surveycriteriagender extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int surveycriteriagenderid;
     private int surveycriteriaid;
     private int gender;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Surveycriteriagender get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Surveycriteriagender");
        try {
            logger.debug("Surveycriteriagender.get(" + id + ") called.");
            Surveycriteriagender obj = (Surveycriteriagender) HibernateUtil.getSession().get(Surveycriteriagender.class, id);
            if (obj == null) {
                logger.debug("Surveycriteriagender.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveycriteriagender();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveycriteriagender", ex);
            return new Surveycriteriagender();
        }
    }

    // Constructors

    /** default constructor */
    public Surveycriteriagender() {
    }




    // Property accessors

    public int getSurveycriteriagenderid() {
        return surveycriteriagenderid;
    }

    public void setSurveycriteriagenderid(int surveycriteriagenderid) {
        this.surveycriteriagenderid = surveycriteriagenderid;
    }

    public int getSurveycriteriaid() {
        return surveycriteriaid;
    }

    public void setSurveycriteriaid(int surveycriteriaid) {
        this.surveycriteriaid = surveycriteriaid;
    }

    public int getGender() {
        return gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }


}
