package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Surveycriteriacity extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int surveycriteriacityid;
     private int surveycriteriaid;
     private int city;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Surveycriteriacity get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Surveycriteriacity");
        try {
            logger.debug("Surveycriteriacity.get(" + id + ") called.");
            Surveycriteriacity obj = (Surveycriteriacity) HibernateUtil.getSession().get(Surveycriteriacity.class, id);
            if (obj == null) {
                logger.debug("Surveycriteriacity.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveycriteriacity();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveycriteriacity", ex);
            return new Surveycriteriacity();
        }
    }

    // Constructors

    /** default constructor */
    public Surveycriteriacity() {
    }




    // Property accessors

    public int getSurveycriteriacityid() {
        return surveycriteriacityid;
    }

    public void setSurveycriteriacityid(int surveycriteriacityid) {
        this.surveycriteriacityid = surveycriteriacityid;
    }

    public int getSurveycriteriaid() {
        return surveycriteriaid;
    }

    public void setSurveycriteriaid(int surveycriteriaid) {
        this.surveycriteriaid = surveycriteriaid;
    }

    public int getCity() {
        return city;
    }

    public void setCity(int city) {
        this.city = city;
    }


}
