package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

/**
 * Blogger generated by hbm2java
 */

public class Surveypanel extends BasePersistentClass implements java.io.Serializable, AuthControlled {

    // Fields
     private int surveypanelid;
     private int surveyid;
     private int panelid;



    public static Surveypanel get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Surveypanel");
        try {
            logger.debug("Surveypanel.get(" + id + ") called.");
            Surveypanel obj = (Surveypanel) HibernateUtil.getSession().get(Surveypanel.class, id);
            if (obj == null) {
                logger.debug("Surveypanel.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveypanel();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveypanel", ex);
            return new Surveypanel();
        }
    }

    // Constructors

    /** default constructor */
    public Surveypanel() {
    }


    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }



    // Property accessors


    public int getSurveypanelid() {
        return surveypanelid;
    }

    public void setSurveypanelid(int surveypanelid) {
        this.surveypanelid = surveypanelid;
    }

    public int getSurveyid() {
        return surveyid;
    }

    public void setSurveyid(int surveyid) {
        this.surveyid = surveyid;
    }

    public int getPanelid() {
        return panelid;
    }

    public void setPanelid(int panelid) {
        this.panelid = panelid;
    }
}
