package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.scheduledjobs.CurrentBalanceUpdater;
import com.dneero.session.AuthControlled;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

/**
 * Blogger generated by hbm2java
 */

public class Surveyincentive extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
    private int surveyincentiveid;
    private int surveyid;
    private int type;

    private Set<Surveyincentiveoption> surveyincentiveoptions = new HashSet<Surveyincentiveoption>();


    public static Surveyincentive get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Surveyincentive");
        try {
            logger.debug("Surveyincentive.get(" + id + ") called.");
            Surveyincentive obj = (Surveyincentive) HibernateUtil.getSession().get(Surveyincentive.class, id);
            if (obj == null) {
                logger.debug("Surveyincentive.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveyincentive();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveyincentive", ex);
            return new Surveyincentive();
        }
    }

    public void save() throws GeneralException {

    }

    public void delete() throws HibernateException {

    }

    // Constructors

    /** default constructor */
    public Surveyincentive() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getSurveyincentiveid() {
        return surveyincentiveid;
    }

    public void setSurveyincentiveid(int surveyincentiveid) {
        this.surveyincentiveid=surveyincentiveid;
    }

    public int getSurveyid() {
        return surveyid;
    }

    public void setSurveyid(int surveyid) {
        this.surveyid=surveyid;
    }

    public Set<Surveyincentiveoption> getSurveyincentiveoptions() {
        return surveyincentiveoptions;
    }

    public void setSurveyincentiveoptions(Set<Surveyincentiveoption> surveyincentiveoptions) {
        this.surveyincentiveoptions=surveyincentiveoptions;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type=type;
    }
}