package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Surveycriteriamaritalstatus extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int surveycriteriamaritalstatusid;
     private int surveycriteriaid;
     //Value drawn from com.dneero.Blogger
     private int maritalstatus;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Surveycriteriamaritalstatus get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Surveycriteriamaritalstatus");
        try {
            logger.debug("Surveycriteriamaritalstatus.get(" + id + ") called.");
            Surveycriteriamaritalstatus obj = (Surveycriteriamaritalstatus) HibernateUtil.getSession().get(Surveycriteriamaritalstatus.class, id);
            if (obj == null) {
                logger.debug("Surveycriteriamaritalstatus.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveycriteriamaritalstatus();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveycriteriamaritalstatus", ex);
            return new Surveycriteriamaritalstatus();
        }
    }

    // Constructors

    /** default constructor */
    public Surveycriteriamaritalstatus() {
    }




    // Property accessors

    public int getSurveycriteriamaritalstatusid() {
        return surveycriteriamaritalstatusid;
    }

    public void setSurveycriteriamaritalstatusid(int surveycriteriamaritalstatusid) {
        this.surveycriteriamaritalstatusid = surveycriteriamaritalstatusid;
    }

    public int getSurveycriteriaid() {
        return surveycriteriaid;
    }

    public void setSurveycriteriaid(int surveycriteriaid) {
        this.surveycriteriaid = surveycriteriaid;
    }

    public int getMaritalstatus() {
        return maritalstatus;
    }

    public void setMaritalstatus(int maritalstatus) {
        this.maritalstatus = maritalstatus;
    }


}
