package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Surveycriteria extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int surveycriteriaid;
     private int surveyid;
     private int agemin;
     private int agemax;

    private Set<Surveycriteriagender> surveycriteriagender = new HashSet<Surveycriteriagender>();
    private Set<Surveycriteriaethnicity> surveycriteriaethnicity = new HashSet<Surveycriteriaethnicity>();
    private Set<Surveycriteriamaritalstatus> surveycriteriamaritalstatus = new HashSet<Surveycriteriamaritalstatus>();
    private Set<Surveycriteriaincomerange> surveycriteriaincomerange = new HashSet<Surveycriteriaincomerange>();
    private Set<Surveycriteriaeducationlevel> surveycriteriaeducationlevel = new HashSet<Surveycriteriaeducationlevel>();
    private Set<Surveycriteriastate> surveycriteriastate = new HashSet<Surveycriteriastate>();
    private Set<Surveycriteriacity> surveycriteriacity = new HashSet<Surveycriteriacity>();
    private Set<Surveycriteriaprofession> surveycriteriaprofession = new HashSet<Surveycriteriaprofession>();
    private Set<Surveycriteriablogfocus> surveycriteriablogfocus = new HashSet<Surveycriteriablogfocus>();
    private Set<Surveycriteriapolitics> surveycriteriapolitics = new HashSet<Surveycriteriapolitics>();




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Surveycriteria get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Survey");
        try {
            logger.debug("Surveycriteria.get(" + id + ") called.");
            Surveycriteria obj = (Surveycriteria) HibernateUtil.getSession().get(Surveycriteria.class, id);
            if (obj == null) {
                logger.debug("Surveycriteria.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveycriteria();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveycriteria", ex);
            return new Surveycriteria();
        }
    }

    // Constructors

    /** default constructor */
    public Surveycriteria() {
    }




    // Property accessors

    public int getSurveycriteriaid() {
        return surveycriteriaid;
    }

    public void setSurveycriteriaid(int surveycriteriaid) {
        this.surveycriteriaid = surveycriteriaid;
    }

    public int getSurveyid() {
        return surveyid;
    }

    public void setSurveyid(int surveyid) {
        this.surveyid = surveyid;
    }

    public int getAgemin() {
        return agemin;
    }

    public void setAgemin(int agemin) {
        this.agemin = agemin;
    }

    public int getAgemax() {
        return agemax;
    }

    public void setAgemax(int agemax) {
        this.agemax = agemax;
    }


    public Set<Surveycriteriagender> getSurveycriteriagender() {
        return surveycriteriagender;
    }

    public void setSurveycriteriagender(Set<Surveycriteriagender> surveycriteriagender) {
        this.surveycriteriagender = surveycriteriagender;
    }

    public Set<Surveycriteriaethnicity> getSurveycriteriaethnicity() {
        return surveycriteriaethnicity;
    }

    public void setSurveycriteriaethnicity(Set<Surveycriteriaethnicity> surveycriteriaethnicity) {
        this.surveycriteriaethnicity = surveycriteriaethnicity;
    }

    public Set<Surveycriteriamaritalstatus> getSurveycriteriamaritalstatus() {
        return surveycriteriamaritalstatus;
    }

    public void setSurveycriteriamaritalstatus(Set<Surveycriteriamaritalstatus> surveycriteriamaritalstatus) {
        this.surveycriteriamaritalstatus = surveycriteriamaritalstatus;
    }

    public Set<Surveycriteriaincomerange> getSurveycriteriaincomerange() {
        return surveycriteriaincomerange;
    }

    public void setSurveycriteriaincomerange(Set<Surveycriteriaincomerange> surveycriteriaincomerange) {
        this.surveycriteriaincomerange = surveycriteriaincomerange;
    }

    public Set<Surveycriteriaeducationlevel> getSurveycriteriaeducationlevel() {
        return surveycriteriaeducationlevel;
    }

    public void setSurveycriteriaeducationlevel(Set<Surveycriteriaeducationlevel> surveycriteriaeducationlevel) {
        this.surveycriteriaeducationlevel = surveycriteriaeducationlevel;
    }

    public Set<Surveycriteriastate> getSurveycriteriastate() {
        return surveycriteriastate;
    }

    public void setSurveycriteriastate(Set<Surveycriteriastate> surveycriteriastate) {
        this.surveycriteriastate = surveycriteriastate;
    }

    public Set<Surveycriteriacity> getSurveycriteriacity() {
        return surveycriteriacity;
    }

    public void setSurveycriteriacity(Set<Surveycriteriacity> surveycriteriacity) {
        this.surveycriteriacity = surveycriteriacity;
    }

    public Set<Surveycriteriaprofession> getSurveycriteriaprofession() {
        return surveycriteriaprofession;
    }

    public void setSurveycriteriaprofession(Set<Surveycriteriaprofession> surveycriteriaprofession) {
        this.surveycriteriaprofession = surveycriteriaprofession;
    }

    public Set<Surveycriteriablogfocus> getSurveycriteriablogfocus() {
        return surveycriteriablogfocus;
    }

    public void setSurveycriteriablogfocus(Set<Surveycriteriablogfocus> surveycriteriablogfocus) {
        this.surveycriteriablogfocus = surveycriteriablogfocus;
    }

    public Set<Surveycriteriapolitics> getSurveycriteriapolitics() {
        return surveycriteriapolitics;
    }

    public void setSurveycriteriapolitics(Set<Surveycriteriapolitics> surveycriteriapolitics) {
        this.surveycriteriapolitics = surveycriteriapolitics;
    }

}
