package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Surveycriteriaincomerange extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int surveycriteriaincomerangeid;
     private int surveycriteriaid;
     //Value of ethnicity drawn from com.dneero.Blogger
     private int incomerange;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Surveycriteriaincomerange get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Surveycriteriaincomerange");
        try {
            logger.debug("Surveycriteriaincomerange.get(" + id + ") called.");
            Surveycriteriaincomerange obj = (Surveycriteriaincomerange) HibernateUtil.getSession().get(Surveycriteriaincomerange.class, id);
            if (obj == null) {
                logger.debug("Surveycriteriaincomerange.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveycriteriaincomerange();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveycriteriaincomerange", ex);
            return new Surveycriteriaincomerange();
        }
    }

    // Constructors

    /** default constructor */
    public Surveycriteriaincomerange() {
    }




    // Property accessors

    public int getSurveycriteriaincomerangeid() {
        return surveycriteriaincomerangeid;
    }

    public void setSurveycriteriaincomerangeid(int surveycriteriaincomerangeid) {
        this.surveycriteriaincomerangeid = surveycriteriaincomerangeid;
    }

    public int getSurveycriteriaid() {
        return surveycriteriaid;
    }

    public void setSurveycriteriaid(int surveycriteriaid) {
        this.surveycriteriaid = surveycriteriaid;
    }

    public int getIncomerange() {
        return incomerange;
    }

    public void setIncomerange(int incomerange) {
        this.incomerange = incomerange;
    }


}
