package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;

/**
 * Survey generated by hbm2java
 */

public class Surveycriteriablogfocus extends BasePersistentClass implements java.io.Serializable, RegerEntity {


    // Fields

     private int surveycriteriablogfocusid;
     private int surveycriteriaid;
     private int blogfocus;




    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static Surveycriteriablogfocus get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Surveycriteriablogfocus");
        try {
            logger.debug("Surveycriteriablogfocus.get(" + id + ") called.");
            Surveycriteriablogfocus obj = (Surveycriteriablogfocus) HibernateUtil.getSession().get(Surveycriteriablogfocus.class, id);
            if (obj == null) {
                logger.debug("Surveycriteriablogfocus.get(" + id + ") returning new instance because hibernate returned null.");
                return new Surveycriteriablogfocus();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Surveycriteriablogfocus", ex);
            return new Surveycriteriablogfocus();
        }
    }

    // Constructors

    /** default constructor */
    public Surveycriteriablogfocus() {
    }




    // Property accessors

    public int getSurveycriteriablogfocusid() {
        return surveycriteriablogfocusid;
    }

    public void setSurveycriteriablogfocusid(int surveycriteriablogfocusid) {
        this.surveycriteriablogfocusid = surveycriteriablogfocusid;
    }

    public int getSurveycriteriaid() {
        return surveycriteriaid;
    }

    public void setSurveycriteriaid(int surveycriteriaid) {
        this.surveycriteriaid = surveycriteriaid;
    }

    public int getBlogfocus() {
        return blogfocus;
    }

    public void setBlogfocus(int blogfocus) {
        this.blogfocus = blogfocus;
    }


}
