package com.dneero.dao;
// Generated Apr 17, 2006 3:45:24 PM by Hibernate Tools 3.1.0.beta4

import com.dneero.cache.providers.CacheFactory;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.dao.hibernate.HibernateUtilDbcache;
import com.dneero.dao.hibernate.HibernateUtilImpressions;
import com.dneero.incentive.Incentive;
import com.dneero.incentive.IncentiveFactory;
import com.dneero.money.SurveyMoneyStatus;
import com.dneero.session.AuthControlled;
import com.dneero.util.GeneralException;
import com.dneero.survey.servlet.EmbedCacheFlusher;
import com.dneero.incentivetwit.Incentivetwit;
import com.dneero.incentivetwit.IncentivetwitFactory;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;

import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;


/**
 * Survey generated by hbm2java
 */

public class Twitask extends BasePersistentClass implements java.io.Serializable, AuthControlled {

    public static int STATUS_DRAFT = 1;
    public static int STATUS_WAITINGFORAPPROVAL = 2;
    public static int STATUS_WAITINGFORSTARTDATE = 3;
    public static int STATUS_WAITINGFORFUNDS = 4;
    public static int STATUS_REJECTED = 5;
    public static int STATUS_OPEN = 6;
    public static int STATUS_CLOSED = 7;


     //Fields
     private int twitaskid;
     private int userid;
     private int plid = 1;
     private String question;
     private String criteriaxml;
     private int numberofrespondentsrequested  = 1000;
     private double willingtopaypertwit = .10;
     private Date startdate;
     private Date senttotwitterdate;
     private Date closedintwitterdate;
     private int status;
     private boolean ischarityonly = false;
     private String charitycustom = "";
     private String charitycustomurl = "";
     private boolean charityonlyallowcustom=false;
     private double dneeromarkuppercent= SurveyMoneyStatus.DEFAULTDNEEROMARKUPPERCENT;
     private boolean issysadminreviewed;
     private boolean issysadminrejected;
     private String resellercode;
     private int scorebysysadmin;
     private Set<Twitanswer> twitanswers = new HashSet<Twitanswer>();
     private Set<Twitaskincentive> twitaskincentives = new HashSet<Twitaskincentive>();
     private Incentivetwit incentivetwit;
     private long twitterid;

    public static Twitask get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Twitask");
        try {
            logger.debug("Twitask.get(" + id + ") called.");
            Twitask obj = (Twitask) HibernateUtil.getSession().get(Twitask.class, id);
            if (obj == null) {
                logger.debug("Twitask.get(" + id + ") returning new instance because hibernate returned null.");
                return new Twitask();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Twitask", ex);
            return new Twitask();
        }
    }

    // Constructors

    /** default constructor */
    public Twitask() {
    }



    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }




    public Incentivetwit getIncentive(){
        //It's been called already for this object so let's just use the one we got last time
        if (incentivetwit!=null){
            return incentivetwit;
        }
        //Gonna have to find one
        Incentivetwit incentiveOut = null;
        if (twitaskincentives!=null && twitaskincentives.size()>0){
            //Just get last.
            //@todo Could add Surveyincentive.isactive flag at some point
            Twitaskincentive si = null;
            for (Iterator<Twitaskincentive> siIterator=twitaskincentives.iterator(); siIterator.hasNext();) {
                Twitaskincentive surveyincentive=siIterator.next();
                if (si==null || surveyincentive.getTwitaskincentiveid()>si.getTwitaskincentiveid()){
                    si = surveyincentive;
                }
            }
            incentiveOut = IncentivetwitFactory.getById(si.getType(), si);
        }
        if (incentiveOut==null){
            incentiveOut =IncentivetwitFactory.getDefaultIncentive();
        }
        return incentiveOut;
    }





    // Property accessors

    public int getTwitaskid() {
        return twitaskid;
    }

    public void setTwitaskid(int twitaskid) {
        this.twitaskid=twitaskid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public int getPlid() {
        return plid;
    }

    public void setPlid(int plid) {
        this.plid=plid;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question=question;
    }

    public String getCriteriaxml() {
        return criteriaxml;
    }

    public void setCriteriaxml(String criteriaxml) {
        this.criteriaxml=criteriaxml;
    }

    public int getNumberofrespondentsrequested() {
        return numberofrespondentsrequested;
    }

    public void setNumberofrespondentsrequested(int numberofrespondentsrequested) {
        this.numberofrespondentsrequested=numberofrespondentsrequested;
    }

    public double getWillingtopaypertwit() {
        return willingtopaypertwit;
    }

    public void setWillingtopaypertwit(double willingtopaypertwit) {
        this.willingtopaypertwit=willingtopaypertwit;
    }

    public Date getStartdate() {
        return startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate=startdate;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status=status;
    }

    public boolean getIscharityonly() {
        return ischarityonly;
    }

    public void setIscharityonly(boolean ischarityonly) {
        this.ischarityonly=ischarityonly;
    }

    public String getCharitycustom() {
        return charitycustom;
    }

    public void setCharitycustom(String charitycustom) {
        this.charitycustom=charitycustom;
    }

    public String getCharitycustomurl() {
        return charitycustomurl;
    }

    public void setCharitycustomurl(String charitycustomurl) {
        this.charitycustomurl=charitycustomurl;
    }

    public boolean getCharityonlyallowcustom() {
        return charityonlyallowcustom;
    }

    public void setCharityonlyallowcustom(boolean charityonlyallowcustom) {
        this.charityonlyallowcustom=charityonlyallowcustom;
    }

    public double getDneeromarkuppercent() {
        return dneeromarkuppercent;
    }

    public void setDneeromarkuppercent(double dneeromarkuppercent) {
        this.dneeromarkuppercent=dneeromarkuppercent;
    }

    public boolean getIssysadminreviewed() {
        return issysadminreviewed;
    }

    public void setIssysadminreviewed(boolean issysadminreviewed) {
        this.issysadminreviewed=issysadminreviewed;
    }

    public boolean getIssysadminrejected() {
        return issysadminrejected;
    }

    public void setIssysadminrejected(boolean issysadminrejected) {
        this.issysadminrejected=issysadminrejected;
    }

    public Set<Twitanswer> getTwitanswers() {
        return twitanswers;
    }

    public void setTwitanswers(Set<Twitanswer> twitanswers) {
        this.twitanswers=twitanswers;
    }

    public String getResellercode() {
        return resellercode;
    }

    public void setResellercode(String resellercode) {
        this.resellercode=resellercode;
    }

    public int getScorebysysadmin() {
        return scorebysysadmin;
    }

    public void setScorebysysadmin(int scorebysysadmin) {
        this.scorebysysadmin=scorebysysadmin;
    }

    public Set<Twitaskincentive> getTwitaskincentives() {
        return twitaskincentives;
    }

    public void setTwitaskincentives(Set<Twitaskincentive> twitaskincentives) {
        this.twitaskincentives=twitaskincentives;
    }

    public Incentivetwit getIncentivetwit() {
        return incentivetwit;
    }

    public void setIncentivetwit(Incentivetwit incentivetwit) {
        this.incentivetwit=incentivetwit;
    }

    public Date getClosedintwitterdate() {
        return closedintwitterdate;
    }

    public void setClosedintwitterdate(Date closedintwitterdate) {
        this.closedintwitterdate=closedintwitterdate;
    }

    public Date getSenttotwitterdate() {
        return senttotwitterdate;
    }

    public void setSenttotwitterdate(Date senttotwitterdate) {
        this.senttotwitterdate=senttotwitterdate;
    }

    public long getTwitterid() {
        return twitterid;
    }

    public void setTwitterid(long twitterid) {
        this.twitterid=twitterid;
    }
}