package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.scheduledjobs.CurrentBalanceUpdater;
import com.dneero.session.AuthControlled;
import com.dneero.util.GeneralException;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

/**
 * Blogger generated by hbm2java
 */

public class Twitaskincentive extends BasePersistentClass implements java.io.Serializable, AuthControlled {


    // Fields
    private int twitaskincentiveid;
    private int twitaskid;
    private int type;

    private Set<Twitaskincentiveoption> twitaskincentiveoptions = new HashSet<Twitaskincentiveoption>();


    public static Twitaskincentive get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Twitaskincentive");
        try {
            logger.debug("Twitaskincentive.get(" + id + ") called.");
            Twitaskincentive obj = (Twitaskincentive) HibernateUtil.getSession().get(Twitaskincentive.class, id);
            if (obj == null) {
                logger.debug("Twitaskincentive.get(" + id + ") returning new instance because hibernate returned null.");
                return new Twitaskincentive();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Twitaskincentive", ex);
            return new Twitaskincentive();
        }
    }



    // Constructors

    /** default constructor */
    public Twitaskincentive() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getTwitaskincentiveid() {
        return twitaskincentiveid;
    }

    public void setTwitaskincentiveid(int twitaskincentiveid) {
        this.twitaskincentiveid=twitaskincentiveid;
    }

    public int getTwitaskid() {
        return twitaskid;
    }

    public void setTwitaskid(int twitaskid) {
        this.twitaskid=twitaskid;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type=type;
    }

    public Set<Twitaskincentiveoption> getTwitaskincentiveoptions() {
        return twitaskincentiveoptions;
    }

    public void setTwitaskincentiveoptions(Set<Twitaskincentiveoption> twitaskincentiveoptions) {
        this.twitaskincentiveoptions=twitaskincentiveoptions;
    }
}