package com.dneero.dao;

import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import com.dneero.incentivetwit.Incentivetwit;
import com.dneero.incentivetwit.IncentivetwitFactory;
import org.apache.log4j.Logger;
import java.util.Date;

/**
 * Blogger generated by hbm2java
 */

public class Twitanswer extends BasePersistentClass implements java.io.Serializable, AuthControlled {

    public static int STATUS_TOOLATE = 1;
    public static int STATUS_DOESNTQUALIFY = 2;
    public static int STATUS_NOBLOGGER = 3;
    public static int STATUS_ALREADYANSWERED = 4;
    public static int STATUS_PENDINGREVIEW = 5;
    public static int STATUS_REJECTED = 6;
    public static int STATUS_APPROVED = 7;
    public static int STATUS_NOTWITASK = 8;


    // Fields
     private int twitanswerid;
     private int twitaskid;
     private int userid;
     private String answer;
     private String twitterusername;
     private Date responsedate;
     private Twitask twitask;
     private boolean isforcharity;
     private String charityname;
     private int status;
     private boolean ispaid;
     private boolean isresearcherreviewed;
     private boolean issysadminreviewed;
     private boolean isresearcherrejected;
     private boolean issysadminrejected;
     private int scorebyresearcher;
     private int scorebysysadmin;
     private long twitterid;
     private long twitterinreplytostatusid;
     private Date twittercreatedate;
     private String twittertext;
     private String twitterprofileimageurl;
     private Twitaskincentive twitaskincentive;
     private int twitaskincentiveid;
     private boolean iscriteriaxmlqualified;
     private int twitterfollowerscount;



    public static Twitanswer get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.Twitanswer");
        try {
            logger.debug("Twitanswer.get(" + id + ") called.");
            Twitanswer obj = (Twitanswer) HibernateUtil.getSession().get(Twitanswer.class, id);
            if (obj == null) {
                logger.debug("Twitanswer.get(" + id + ") returning new instance because hibernate returned null.");
                return new Twitanswer();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.Twitanswer", ex);
            return new Twitanswer();
        }
    }

    // Constructors

    /** default constructor */
    public Twitanswer() {
    }


    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }


    public Incentivetwit getIncentive(){
        Incentivetwit incentiveOut = null;
        if (getTwitaskincentive()!=null && getTwitaskincentive().getTwitaskincentiveid()>0){
            incentiveOut = IncentivetwitFactory.getById(getTwitaskincentive().getType(), getTwitaskincentive());
        }
        if (incentiveOut==null){
            incentiveOut =IncentivetwitFactory.getDefaultIncentive();
        }
        return incentiveOut;
    }


    // Property accessors

    public Twitaskincentive getTwitaskincentive() {
        return twitaskincentive;
    }

    public void setTwitaskincentive(Twitaskincentive twitaskincentive) {
        this.twitaskincentive=twitaskincentive;
    }

    public int getTwitanswerid() {
        return twitanswerid;
    }

    public void setTwitanswerid(int twitanswerid) {
        this.twitanswerid=twitanswerid;
    }

    public int getTwitaskid() {
        return twitaskid;
    }

    public void setTwitaskid(int twitaskid) {
        this.twitaskid=twitaskid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer=answer;
    }

    public String getTwitterusername() {
        return twitterusername;
    }

    public void setTwitterusername(String twitterusername) {
        this.twitterusername=twitterusername;
    }

    public Date getResponsedate() {
        return responsedate;
    }

    public void setResponsedate(Date responsedate) {
        this.responsedate=responsedate;
    }

    public Twitask getTwitask() {
        return twitask;
    }

    public void setTwitask(Twitask twitask) {
        this.twitask=twitask;
    }

    public boolean getIsforcharity() {
        return isforcharity;
    }

    public void setIsforcharity(boolean isforcharity) {
        this.isforcharity=isforcharity;
    }

    public String getCharityname() {
        return charityname;
    }

    public void setCharityname(String charityname) {
        this.charityname=charityname;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status=status;
    }

    public boolean getIspaid() {
        return ispaid;
    }

    public void setIspaid(boolean ispaid) {
        this.ispaid=ispaid;
    }

    public boolean getIsresearcherreviewed() {
        return isresearcherreviewed;
    }

    public void setIsresearcherreviewed(boolean isresearcherreviewed) {
        this.isresearcherreviewed=isresearcherreviewed;
    }

    public boolean getIssysadminreviewed() {
        return issysadminreviewed;
    }

    public void setIssysadminreviewed(boolean issysadminreviewed) {
        this.issysadminreviewed=issysadminreviewed;
    }

    public boolean getIsresearcherrejected() {
        return isresearcherrejected;
    }

    public void setIsresearcherrejected(boolean isresearcherrejected) {
        this.isresearcherrejected=isresearcherrejected;
    }

    public boolean getIssysadminrejected() {
        return issysadminrejected;
    }

    public void setIssysadminrejected(boolean issysadminrejected) {
        this.issysadminrejected=issysadminrejected;
    }

    public int getScorebyresearcher() {
        return scorebyresearcher;
    }

    public void setScorebyresearcher(int scorebyresearcher) {
        this.scorebyresearcher=scorebyresearcher;
    }

    public int getScorebysysadmin() {
        return scorebysysadmin;
    }

    public void setScorebysysadmin(int scorebysysadmin) {
        this.scorebysysadmin=scorebysysadmin;
    }

    public long getTwitterid() {
        return twitterid;
    }

    public void setTwitterid(long twitterid) {
        this.twitterid=twitterid;
    }

    public long getTwitterinreplytostatusid() {
        return twitterinreplytostatusid;
    }

    public void setTwitterinreplytostatusid(long twitterinreplytostatusid) {
        this.twitterinreplytostatusid=twitterinreplytostatusid;
    }

    public Date getTwittercreatedate() {
        return twittercreatedate;
    }

    public void setTwittercreatedate(Date twittercreatedate) {
        this.twittercreatedate=twittercreatedate;
    }

    public String getTwittertext() {
        return twittertext;
    }

    public void setTwittertext(String twittertext) {
        this.twittertext=twittertext;
    }

    public int getTwitaskincentiveid() {
        return twitaskincentiveid;
    }

    public void setTwitaskincentiveid(int twitaskincentiveid) {
        this.twitaskincentiveid=twitaskincentiveid;
    }

    public boolean getIscriteriaxmlqualified() {
        return iscriteriaxmlqualified;
    }

    public void setIscriteriaxmlqualified(boolean iscriteriaxmlqualified) {
        this.iscriteriaxmlqualified=iscriteriaxmlqualified;
    }

    public String getTwitterprofileimageurl() {
        return twitterprofileimageurl;
    }

    public void setTwitterprofileimageurl(String twitterprofileimageurl) {
        this.twitterprofileimageurl=twitterprofileimageurl;
    }

    public int getTwitterfollowerscount() {
        return twitterfollowerscount;
    }

    public void setTwitterfollowerscount(int twitterfollowerscount) {
        this.twitterfollowerscount=twitterfollowerscount;
    }
}