package com.dneero.dao;

import com.dneero.util.GeneralException;
import com.dneero.dao.hibernate.BasePersistentClass;
import com.dneero.dao.hibernate.RegerEntity;
import com.dneero.dao.hibernate.HibernateUtil;
import com.dneero.session.AuthControlled;
import org.apache.log4j.Logger;

import java.util.Set;
import java.util.HashSet;
import java.util.Date;
// Generated Apr 17, 2006 3:45:25 PM by Hibernate Tools 3.1.0.beta4



/**
 * User generated by hbm2java
 */

public class User extends BasePersistentClass implements java.io.Serializable, RegerEntity, AuthControlled {


    // Fields    

     private int userid;
     private int referredbyuserid;
     private boolean isqualifiedforrevshare;
     private String email;
     private String password;
     private String firstname;
     private String lastname;
     private boolean isactivatedbyemail;
     private String emailactivationkey;
     private Date emailactivationlastsent;
     private Date createdate;
     private int paymethod;
     private int paymethodcreditcardid;
     private String paymethodpaypaladdress;
     private int chargemethod;
     private int chargemethodcreditcardid;

     //Association
    private Set<Userrole> userroles = new HashSet<Userrole>();
    public Set<Userrole> getUserroles() {
        return userroles;
    }
    public void setUserroles(Set<Userrole> userroles) {
        this.userroles = userroles;
    }

    private Set<Usereula> usereulas = new HashSet<Usereula>();
    public Set<Usereula> getUsereulas() {
        return usereulas;
    }
    public void setUsereulas(Set<Usereula> usereulas) {
        this.usereulas = usereulas;
    }

    private Blogger blogger;
    public Blogger getBlogger() {
        return blogger;
    }
    public void setBlogger(Blogger blogger) {
        this.blogger = blogger;
    }
    
    private Researcher researcher;
    public Researcher getResearcher() {
        return researcher;
    }
    public void setResearcher(Researcher researcher) {
        this.researcher = researcher;
    }

    private Set<Responsepending> responsependings = new HashSet<Responsepending>();
    public Set<Responsepending> getResponsependings() {
        return responsependings;
    }
    public void setResponsependings(Set<Responsepending> responsependings) {
        this.responsependings = responsependings;
    }

    //Validator
    public void validateRegerEntity() throws GeneralException {

    }

    //Loader
    public void load(){

    }

    public static User get(int id) {
        Logger logger = Logger.getLogger("com.dneero.dao.User");
        try {
            logger.debug("User.get(" + id + ") called.");
            User obj = (User) HibernateUtil.getSession().get(User.class, id);
            if (obj == null) {
                logger.debug("User.get(" + id + ") returning new instance because hibernate returned null.");
                return new User();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.dneero.dao.User", ex);
            return new User();
        }
    }

    // Constructors

    /** default constructor */
    public User() {
    }

    public boolean canRead(User user){
        if (user.getUserid()==userid){
            return true;
        }
        return false;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }

    
    /** full constructor */
    public User(int userid, String email, String password, String firstname, String lastname) {
        this.userid = userid;
        this.email = email;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
    }
    

   
    // Property accessors

    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }

    public int getReferredbyuserid() {
        return referredbyuserid;
    }

    public void setReferredbyuserid(int referredbyuserid) {
        this.referredbyuserid = referredbyuserid;
    }

    public boolean getIsqualifiedforrevshare() {
        return isqualifiedforrevshare;
    }

    public void setIsqualifiedforrevshare(boolean isqualifiedforrevshare) {
        this.isqualifiedforrevshare = isqualifiedforrevshare;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public boolean getIsactivatedbyemail() {
        return isactivatedbyemail;
    }

    public void setIsactivatedbyemail(boolean isactivatedbyemail) {
        this.isactivatedbyemail = isactivatedbyemail;
    }

    public String getEmailactivationkey() {
        return emailactivationkey;
    }

    public void setEmailactivationkey(String emailactivationkey) {
        this.emailactivationkey = emailactivationkey;
    }

    public Date getEmailactivationlastsent() {
        return emailactivationlastsent;
    }

    public void setEmailactivationlastsent(Date emailactivationlastsent) {
        this.emailactivationlastsent = emailactivationlastsent;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }


    public int getPaymethod() {
        return paymethod;
    }

    public void setPaymethod(int paymethod) {
        this.paymethod = paymethod;
    }

    public String getPaymethodpaypaladdress() {
        return paymethodpaypaladdress;
    }

    public void setPaymethodpaypaladdress(String paymethodpaypaladdress) {
        this.paymethodpaypaladdress = paymethodpaypaladdress;
    }



    public int getChargemethod() {
        return chargemethod;
    }

    public void setChargemethod(int chargemethod) {
        this.chargemethod = chargemethod;
    }


    public int getPaymethodcreditcardid() {
        return paymethodcreditcardid;
    }

    public void setPaymethodcreditcardid(int paymethodcreditcardid) {
        this.paymethodcreditcardid = paymethodcreditcardid;
    }

    public int getChargemethodcreditcardid() {
        return chargemethodcreditcardid;
    }

    public void setChargemethodcreditcardid(int chargemethodcreditcardid) {
        this.chargemethodcreditcardid = chargemethodcreditcardid;
    }
}
