<%@ page import="org.apache.log4j.Logger" %>
<%@ page import="com.dneero.htmluibeans.BloggerEarningsRevshare" %>
<%@ page import="com.dneero.htmluibeans.BloggerEarningsRevshareInvite" %>
<%@ page import="com.dneero.htmluibeans.BloggerEarningsRevshareTreeHandler" %>
<%@ page import="com.dneero.htmlui.*" %>
<%@ page import="java.util.Iterator" %>
<%@ page import="com.dneero.htmluibeans.BloggerEarningsRevshareTreeNode" %>
<%@ page import="com.dneero.util.Str" %>
<%@ page import="com.dneero.dbgrid.GridCol" %>
<%@ page import="java.util.ArrayList" %>
<%@ page import="com.dneero.dbgrid.Grid" %>
<%
Logger logger = Logger.getLogger(this.getClass().getName());
String pagetitle = "Referral Program";
String navtab = "bloggers";
String acl = "blogger";
%>
<%@ include file="/template/auth.jsp" %>
<%
    BloggerEarningsRevshare bloggerEarningsRevshare=(BloggerEarningsRevshare) Pagez.getBeanMgr().get("BloggerEarningsRevshare");
    BloggerEarningsRevshareInvite bloggerEarningsRevshareInvite=(BloggerEarningsRevshareInvite) Pagez.getBeanMgr().get("BloggerEarningsRevshareInvite");
    BloggerEarningsRevshareTreeHandler bloggerEarningsRevshareTreeHandler=(BloggerEarningsRevshareTreeHandler) Pagez.getBeanMgr().get("BloggerEarningsRevshareTreeHandler");
%>
<%
    if (request.getParameter("action") != null && request.getParameter("action").equals("invite")) {
        try {
            bloggerEarningsRevshareInvite.setEmail(Textarea.getValueFromRequest("email", "Email", true));
            bloggerEarningsRevshareInvite.setMessage(Textarea.getValueFromRequest("message", "Message", false));
            bloggerEarningsRevshareInvite.invite();
            Pagez.getUserSession().setMessage("Invitation(s) sent successfully.");
        } catch (com.dneero.htmlui.ValidationException vex) {
            Pagez.getUserSession().setMessage(vex.getErrorsAsSingleString());
        }
    }
%>
<%@ include file="/template/header.jsp" %>



        <%if (bloggerEarningsRevshare.getMsg()!=null && !bloggerEarningsRevshare.getMsg().equals("")){%>
            <div class="rounded" style="padding: 15px; margin: 5px; background: #F2FFBF;">
                <font class="mediumfont"><%=bloggerEarningsRevshare.getMsg()%></font>
            </div>
        <%}%>


        <table cellpadding="0" cellspacing="0" border="0">
            <tr><td valign="top">
            <div style="background: #ffffff; width: 350px; padding: 20px;">
               <font class="mediumfont">Earn With Your Friends</font>
               <br/>
               <font class="smallfont">We'll pay you a piece of any dNeero earnings generated by friends that you invite to the program... out of our own pocket.  When one of your friends accepts the invitation you'll see them listed to the right... and then you'll be making even more money!</font>
               <br/>
               <br/>
               <font class="smallfont">Here's how it works:</font>
               <ul>
                  <li><font class="smallfont">We calculate your friend's earnings</font></li>
                  <li><font class="smallfont">We pay your friend</font></li>
                  <li><font class="smallfont">We pay you up to <%=bloggerEarningsRevshare.getLevel1percent()%>% of your friend's earnings (out of our pocket)</font></li>
                  <li><font class="smallfont">As your friend invites friends we pay you a percentage of your friend's friends earnings (also out of our pocket, see chart to right)</font></li> 
               </ul>

               <br/>
               <br/>
                <form action="/blogger/bloggerearningsrevshare.jsp" method="post">
                    <input type="hidden" name="dpage" value="/blogger/bloggerearningsrevshare.jsp">
                    <input type="hidden" name="action" value="invite">

                    <table cellpadding="0" cellspacing="0" border="0">

                        <tr>
                            <td valign="top">
                                <font class="formfieldnamefont">Email Addresses</font>
                                <br/>
                                <font class="normalfont">One per line</font>
                            </td>
                            <td valign="top">
                                <%=Textarea.getHtml("email", bloggerEarningsRevshareInvite.getEmail(), 5, 25, "", "")%>
                            </td>
                        </tr>

                        <tr>
                            <td valign="top">
                                <font class="formfieldnamefont">Optional Message</font>
                                <br/>
                                <font class="smallfont">We'll automatically include a link for your friend to click to easily sign up.</font>
                            </td>
                            <td valign="top">
                                <%=Textarea.getHtml("message", bloggerEarningsRevshareInvite.getMessage(), 5, 25, "", "")%>
                            </td>
                        </tr>

                        <tr>
                            <td valign="top">
                            </td>
                            <td valign="top">
                                <input type="submit" class="formsubmitbutton" value="Invite Friends">
                            </td>
                        </tr>

                    </table>

                </form>
            </div>

           </td>
           <td valign="top">
                <div class="rounded" style="background: #e6e6e6; text-align: left; padding: 20px;">
                    <font class="mediumfont">Friends</font>
                    <br/>
                    <font class="smallfont">Listed below are the friends that you've invited (and those that they've invited) to make money using their blog.</font>
                    <br/>
                    <%
                        for (Iterator it=bloggerEarningsRevshareTreeHandler.getTree().iterator(); it.hasNext();) {
                            BloggerEarningsRevshareTreeNode bertn = (BloggerEarningsRevshareTreeNode) it.next();
                            String indent = "<img src=\"/images/clear.gif\" width=\""+(bertn.getLevel()*10)+"\" height=\"1\" alt=\"\"/>";
                            %><br/><%=indent%><font class="tinyfont"><a href="/profile.jsp?userid=<%=bertn.getIdentifier()%>"><%=bertn.getDescription()%></a> ($<%=Str.formatForMoney(bertn.getAmtEarnedFromThisBloggerAllTime())%>)</font><%
                        }
                    %>
                </div>



                <br/>
                <div class="rounded" style="background: #e6e6e6; text-align: left; padding: 20px;">
                <font class="mediumfont">Earn on Your Friend's Friends</font>
                    <br/>
                    <font class="smallfont">You share in the revenue even if your friends do the inviting!  Of course, each level away from you that percentage will be smaller... but those little bits can add up!</font>
                    <br/>
                    <table cellpadding="0" cellspacing="0" border="0">
                        <tr>
                        <td valign="top"> </td>
                        <td valign="top"><font class="mediumfont">You Earn</font></td>
                        </tr>
                        <tr>
                        <td valign="top"><font class="mediumfont">1st Level</font></td>
                        <td valign="top"><font class="normalfont"><%=bloggerEarningsRevshare.getLevel1percent()%> %</font></td>
                        </tr>
                        <tr>
                        <td valign="top"><font class="mediumfont">2nd Level</font></td>
                        <td valign="top"><font class="normalfont"><%=bloggerEarningsRevshare.getLevel2percent()%> %</font></td>
                        </tr>
                        <tr>
                        <td valign="top"><font class="mediumfont">3rd Level</font></td>
                        <td valign="top"><font class="normalfont"><%=bloggerEarningsRevshare.getLevel3percent()%> %</font></td>
                        </tr>
                        <tr>
                        <td valign="top"><font class="mediumfont">4th Level</font></td>
                        <td valign="top"><font class="normalfont"><%=bloggerEarningsRevshare.getLevel4percent()%> %</font></td>
                        </tr>
                        <tr>
                        <td valign="top"><font class="mediumfont">5th Level</font></td>
                        <td valign="top"><font class="normalfont"><%=bloggerEarningsRevshare.getLevel5percent()%> %</font></td>
                        </tr>
                     </table>
                 </div>

               <br/>
                <div class="rounded" style="background: #e6e6e6; text-align: left; padding: 15px;">
                    <font class="mediumfont" style="color: #666666;"><b>Referer Earnings</b></font>
                    <br/>
                    <%if (bloggerEarningsRevshare.getBalances()==null || bloggerEarningsRevshare.getBalances().size()==0){%>
                        <font class="smallfont" style="color: #666666;"><b>You haven't yet earned anything from the Referral Program.</b></font>
                    <%} else {%>
                        <%
                            ArrayList<GridCol> cols = new ArrayList<GridCol>();
                            cols.add(new GridCol("", "<b><$date|" + Grid.GRIDCOLRENDERER_DATETIMECOMPACT + "$></b><br/><$description$>", false, "", "tinyfont", "", ""));
                            cols.add(new GridCol("", "<$amt$>", true, "", "tinyfont"));
                        %>
                        <%=Grid.render(bloggerEarningsRevshare.getBalances(), cols, 50, "/blogger/bloggerearningsrevshare.jsp", "pagebalances")%>
                    <%}%>
                </div>

               <br/>
               <div class="rounded" style="background: #e6e6e6; text-align: left; padding: 20px;">
                    <font class="mediumfont">Don't Miss</font>
                    <font class="smallfont">You may also be interested in the <a href="/account/reseller.jsp">Reseller Program</a> that allows you to make money selling surveys... it's more work... but also more cash!</font>
                </div>

            </td></tr>
        </table>



<%@ include file="/template/footer.jsp" %>


