package com.dneero.constants;

import java.util.TreeSet;

/**
 * User: Joe Reger Jr
 * Date: Nov 9, 2007
 * Time: 12:34:09 PM
 */
public class Cities {

    public static TreeSet<String> get(){
        TreeSet ts = new TreeSet();
        ts.add("Non-US");
        ts.add("Abilene");
        ts.add("Akron");
        ts.add("Albuquerque");
        ts.add("Alexandria");
        ts.add("Allentown");
        ts.add("Amarillo");
        ts.add("Anaheim");
        ts.add("Anchorage");
        ts.add("Ann Arbor");
        ts.add("Arlington VA");
        ts.add("Arlington TX");
        ts.add("Arvada CO");
        ts.add("Athens-Clarke County");
        ts.add("Atlanta");
        ts.add("Augusta-Richmond County");
        ts.add("Aurora CO");
        ts.add("Aurora IL");
        ts.add("Austin");
        ts.add("Bakersfield");
        ts.add("Baltimore");
        ts.add("Baton Rouge");
        ts.add("Beaumont");
        ts.add("Bellevue");
        ts.add("Berkeley");
        ts.add("Birmingham");
        ts.add("Boise City");
        ts.add("Boston");
        ts.add("Bridgeport");
        ts.add("Brownsville");
        ts.add("Buffalo");
        ts.add("Burbank");
        ts.add("Cambridge");
        ts.add("Cape Coral");
        ts.add("Carrollton");
        ts.add("Cedar Rapids");
        ts.add("Chandler");
        ts.add("Charlotte");
        ts.add("Chattanooga");
        ts.add("Chesapeake");
        ts.add("Chicago");
        ts.add("Chula Vista");
        ts.add("Cincinnati");
        ts.add("Clarksville");
        ts.add("Clearwater");
        ts.add("Cleveland");
        ts.add("Colorado Springs");
        ts.add("Columbia");
        ts.add("Columbus GA");
        ts.add("Columbus OH");
        ts.add("Concord");
        ts.add("Coral Springs");
        ts.add("Corona");
        ts.add("Corpus Christi");
        ts.add("Costa Mesa");
        ts.add("Dallas");
        ts.add("Daly City");
        ts.add("Dayton");
        ts.add("Denver");
        ts.add("Des Moines");
        ts.add("Detroit");
        ts.add("Downey");
        ts.add("Durham");
        ts.add("El Monte");
        ts.add("El Paso");
        ts.add("Elizabeth");
        ts.add("Erie");
        ts.add("Escondido");
        ts.add("Eugene");
        ts.add("Evansville");
        ts.add("Fairfield");
        ts.add("Fayetteville");
        ts.add("Flint");
        ts.add("Fontana");
        ts.add("Fort Collins");
        ts.add("Fort Lauderdale");
        ts.add("Fort Wayne");
        ts.add("Fort Worth");
        ts.add("Fremont");
        ts.add("Fresno");
        ts.add("Fullerton");
        ts.add("Garden Grove");
        ts.add("Garland");
        ts.add("Gary");
        ts.add("Gilbert");
        ts.add("Glendale AZ");
        ts.add("Glendale CA");
        ts.add("Grand Prairie TX");
        ts.add("Grand Rapids MI");
        ts.add("Green Bay");
        ts.add("Greensboro");
        ts.add("Hampton");
        ts.add("Hartford");
        ts.add("Hayward");
        ts.add("Henderson");
        ts.add("Hialeah");
        ts.add("Hollywood");
        ts.add("Honolulu");
        ts.add("Houston");
        ts.add("Huntington Beach");
        ts.add("Huntsville");
        ts.add("Independence");
        ts.add("Indianapolis");
        ts.add("Inglewood");
        ts.add("Irvine");
        ts.add("Irving");
        ts.add("Jackson");
        ts.add("Jacksonville");
        ts.add("Jersey City");
        ts.add("Joliet");
        ts.add("Kansas City MO");
        ts.add("Kansas City KA");
        ts.add("Knoxville");
        ts.add("Lafayette");
        ts.add("Lakewood");
        ts.add("Lancaster");
        ts.add("Lansing");
        ts.add("Laredo");
        ts.add("Las Vegas");
        ts.add("Lexington-Fayette");
        ts.add("Lincoln");
        ts.add("Little Rock");
        ts.add("Livonia");
        ts.add("Long Beach");
        ts.add("Los Angeles");
        ts.add("Louisville");
        ts.add("Lowell");
        ts.add("Lubbock");
        ts.add("Madison");
        ts.add("Manchester");
        ts.add("McAllen");
        ts.add("Memphis");
        ts.add("Mesa");
        ts.add("Mesquite");
        ts.add("Miami");
        ts.add("Milwaukee");
        ts.add("Minneapolis");
        ts.add("Mobile");
        ts.add("Modesto");
        ts.add("Montgomery");
        ts.add("Moreno Valley");
        ts.add("Naperville");
        ts.add("Nashville-Davidson");
        ts.add("New Haven");
        ts.add("New Orleans");
        ts.add("New York");
        ts.add("Newark");
        ts.add("Newport News");
        ts.add("Norfolk");
        ts.add("North Las Vegas");
        ts.add("Norwalk");
        ts.add("Oakland");
        ts.add("Oceanside");
        ts.add("Oklahoma City");
        ts.add("Olathe");
        ts.add("Omaha");
        ts.add("Ontario");
        ts.add("Orange");
        ts.add("Orlando");
        ts.add("Overland Park");
        ts.add("Oxnard");
        ts.add("Palmdale");
        ts.add("Pasadena TX");
        ts.add("Pasadena CA");
        ts.add("Paterson");
        ts.add("Pembroke Pines");
        ts.add("Peoria AZ");
        ts.add("Peoria IL");
        ts.add("Philadelphia");
        ts.add("Phoenix");
        ts.add("Pittsburgh");
        ts.add("Plano");
        ts.add("Pomona");
        ts.add("Portland");
        ts.add("Providence");
        ts.add("Provo");
        ts.add("Pueblo");
        ts.add("Raleigh");
        ts.add("Rancho Cucamonga");
        ts.add("Reno");
        ts.add("Richmond VA");
        ts.add("Richmond CA");
        ts.add("Riverside");
        ts.add("Rochester");
        ts.add("Rockford");
        ts.add("Sacramento");
        ts.add("Salem");
        ts.add("Salinas");
        ts.add("Salt Lake City");
        ts.add("San Antonio");
        ts.add("San Bernardino");
        ts.add("San Buenaventura (Ventura)");
        ts.add("San Diego");
        ts.add("San Francisco");
        ts.add("San Jose");
        ts.add("Santa Ana");
        ts.add("Santa Clara");
        ts.add("Santa Clarita");
        ts.add("Santa Rosa");
        ts.add("Savannah");
        ts.add("Scottsdale");
        ts.add("Seattle");
        ts.add("Shreveport");
        ts.add("Simi Valley");
        ts.add("Sioux Falls");
        ts.add("South Bend");
        ts.add("Spokane");
        ts.add("Springfield MA");
        ts.add("Springfield MO");
        ts.add("Springfield IL");
        ts.add("St. Louis");
        ts.add("St. Paul");
        ts.add("St. Petersburg");
        ts.add("Stamford");
        ts.add("Sterling Heights");
        ts.add("Stockton");
        ts.add("Sunnyvale");
        ts.add("Syracuse");
        ts.add("Tacoma");
        ts.add("Tallahassee");
        ts.add("Tampa");
        ts.add("Tempe");
        ts.add("Thousand Oaks");
        ts.add("Toledo");
        ts.add("Topeka");
        ts.add("Torrance");
        ts.add("Tucson");
        ts.add("Tulsa");
        ts.add("Vallejo");
        ts.add("Vancouver");
        ts.add("Virginia Beach");
        ts.add("Waco");
        ts.add("Warren");
        ts.add("Washington");
        ts.add("Waterbury");
        ts.add("West Covina");
        ts.add("West Valley City");
        ts.add("Westminster");
        ts.add("Wichita");
        ts.add("Wichita Falls");
        ts.add("Winston-Salem");
        ts.add("Worcester");
        ts.add("Yonkers");        
        return ts;
    }

}
