package com.dneero.constants;

import java.util.TreeSet;

/**
 * User: Joe Reger Jr
 * Date: Nov 9, 2007
 * Time: 12:34:09 PM
 */
public class Countries {

    public static TreeSet<String> get(){
        TreeSet ts = new TreeSet();
        
        ts.add("United States");
        ts.add("Canada");
        ts.add("Afghanistan");
        ts.add("Albania");
        ts.add("Algeria");
        ts.add("American Samoa");
        ts.add("Andorra");
        ts.add("Angola");
        ts.add("Anguilla");
        ts.add("Antarctica");
        ts.add("Antigua And Barbuda");
        ts.add("Argentina");
        ts.add("Armenia");
        ts.add("Aruba");
        ts.add("Australia");
        ts.add("Austria");
        ts.add("Azerbaijan");
        ts.add("Bahamas");
        ts.add("Bahrain");
        ts.add("Bangladesh");
        ts.add("Barbados");
        ts.add("Belarus");
        ts.add("Belgium");
        ts.add("Belize");
        ts.add("Benin");
        ts.add("Bermuda");
        ts.add("Bhutan");
        ts.add("Bolivia");
        ts.add("Bosnia And Herzegowina");
        ts.add("Botswana");
        ts.add("Bouvet Island");
        ts.add("Brazil");
        ts.add("British Indian Ocean Territory");
        ts.add("Brunei Darussalam");
        ts.add("Bulgaria");
        ts.add("Burkina Faso");
        ts.add("Burundi");
        ts.add("Cambodia");
        ts.add("Cameroon");
        ts.add("Cape Verde");
        ts.add("Cayman Islands");
        ts.add("Central African Republic");
        ts.add("Chad");
        ts.add("Chile");
        ts.add("China");
        ts.add("Christmas Island");
        ts.add("Cocos (Keeling) Islands");
        ts.add("Colombia");
        ts.add("Comoros");
        ts.add("Congo");
        ts.add("Cook Islands");
        ts.add("Costa Rica");
        ts.add("Cote D'Ivoire");
        ts.add("Croatia (Local Name: Hrvatska)");
        ts.add("Cuba");
        ts.add("Cyprus");
        ts.add("Czech Republic");
        ts.add("Denmark");
        ts.add("Djibouti");
        ts.add("Dominica");
        ts.add("Dominican Republic");
        ts.add("East Timor");
        ts.add("Ecuador");
        ts.add("Egypt");
        ts.add("El Salvador");
        ts.add("Equatorial Guinea");
        ts.add("Eritrea");
        ts.add("Estonia");
        ts.add("Ethiopia");
        ts.add("Falkland Islands (Malvinas)");
        ts.add("Faroe Islands");
        ts.add("Fiji");
        ts.add("Finland");
        ts.add("France");
        ts.add("French Guiana");
        ts.add("French Polynesia");
        ts.add("French Southern Territories");
        ts.add("Gabon");
        ts.add("Gambia");
        ts.add("Georgia");
        ts.add("Germany");
        ts.add("Ghana");
        ts.add("Gibraltar");
        ts.add("Greece");
        ts.add("Greenland");
        ts.add("Grenada");
        ts.add("Guadeloupe");
        ts.add("Guam");
        ts.add("Guatemala");
        ts.add("Guinea");
        ts.add("Guinea-Bissau");
        ts.add("Guyana");
        ts.add("Haiti");
        ts.add("Honduras");
        ts.add("Hong Kong");
        ts.add("Hungary");
        ts.add("Icel And");
        ts.add("India");
        ts.add("Indonesia");
        ts.add("Iran (Islamic Republic Of)");
        ts.add("Iraq");
        ts.add("Ireland");
        ts.add("Israel");
        ts.add("Italy");
        ts.add("Jamaica");
        ts.add("Japan");
        ts.add("Jordan");
        ts.add("Kazakhstan");
        ts.add("Kenya");
        ts.add("Kiribati");
        ts.add("Korea");
        ts.add("Kuwait");
        ts.add("Kyrgyzstan");
        ts.add("Lao People'S Dem Republic");
        ts.add("Latvia");
        ts.add("Lebanon");
        ts.add("Lesotho");
        ts.add("Liberia");
        ts.add("Libyan Arab Jamahiriya");
        ts.add("Liechtenstein");
        ts.add("Lithuania");
        ts.add("Luxembourg");
        ts.add("Macau");
        ts.add("Macedonia");
        ts.add("Madagascar");
        ts.add("Malawi");
        ts.add("Malaysia");
        ts.add("Maldives");
        ts.add("Mali");
        ts.add("Malta");
        ts.add("Marshall Islands");
        ts.add("Martinique");
        ts.add("Mauritania");
        ts.add("Mauritius");
        ts.add("Mayotte");
        ts.add("Mexico");
        ts.add("Micronesia, Federated States");
        ts.add("Moldova, Republic Of");
        ts.add("Monaco");
        ts.add("Mongolia");
        ts.add("Montserrat");
        ts.add("Morocco");
        ts.add("Mozambique");
        ts.add("Myanmar");
        ts.add("Namibia");
        ts.add("Nauru");
        ts.add("Nepal");
        ts.add("Netherlands");
        ts.add("Netherlands Ant Illes");
        ts.add("New Caledonia");
        ts.add("New Zealand");
        ts.add("Nicaragua");
        ts.add("Niger");
        ts.add("Nigeria");
        ts.add("Niue");
        ts.add("Norfolk Island");
        ts.add("Northern Mariana Islands");
        ts.add("Norway");
        ts.add("Oman");
        ts.add("Pakistan");
        ts.add("Palau");
        ts.add("Panama");
        ts.add("Papua New Guinea");
        ts.add("Paraguay");
        ts.add("Peru");
        ts.add("Philippines");
        ts.add("Pitcairn");
        ts.add("Poland");
        ts.add("Portugal");
        ts.add("Puerto Rico");
        ts.add("Qatar");
        ts.add("Reunion");
        ts.add("Romania");
        ts.add("Russian Federation");
        ts.add("Rwanda");
        ts.add("Saint K Itts And Nevis");
        ts.add("Saint Lucia");
        ts.add("Saint Vincent, The Grenadines");
        ts.add("Samoa");
        ts.add("San Marino");
        ts.add("Sao Tome And Principe");
        ts.add("Saudi Arabia");
        ts.add("Senegal");
        ts.add("Seychelles");
        ts.add("Sierra Leone");
        ts.add("Singapore");
        ts.add("Slovakia (Slovak Republic)");
        ts.add("Slovenia");
        ts.add("Solomon Islands");
        ts.add("Somalia");
        ts.add("South Africa");
        ts.add("South Georgia , S Sandwich Is.");
        ts.add("Spain");
        ts.add("Sri Lanka");
        ts.add("St. Helena");
        ts.add("St. Pierre And Miquelon");
        ts.add("Sudan");
        ts.add("Suriname");
        ts.add("Svalbard, Jan Mayen Islands");
        ts.add("Sw Aziland");
        ts.add("Sweden");
        ts.add("Switzerland");
        ts.add("Syrian Arab Republic");
        ts.add("Taiwan");
        ts.add("Tajikistan");
        ts.add("Tanzania, United Republic Of");
        ts.add("Thailand");
        ts.add("Togo");
        ts.add("Tokelau");
        ts.add("Tonga");
        ts.add("Trinidad And Tobago");
        ts.add("Tunisia");
        ts.add("Turkey");
        ts.add("Turkmenistan");
        ts.add("Turks And Caicos Islands");
        ts.add("Tuvalu");
        ts.add("Uganda");
        ts.add("Ukraine");
        ts.add("United Arab Emirates");
        ts.add("United Kingdom");
        ts.add("United States Minor Is.");
        ts.add("Uruguay");
        ts.add("Uzbekistan");
        ts.add("Vanuatu");
        ts.add("Venezuela");
        ts.add("Viet Nam");
        ts.add("Virgin Islands (British)");
        ts.add("Virgin Islands (U.S.)");
        ts.add("Wallis And Futuna Islands");
        ts.add("Western Sahara");
        ts.add("Yemen");
        ts.add("Yugoslavia");
        ts.add("Zaire");
        ts.add("Zambia");
        ts.add("Zimbabwe");

        return ts;
    }

}