<%@ page import="org.apache.log4j.Logger" %>
<%@ page import="com.dneero.htmlui.Pagez" %>
<%
Logger logger = Logger.getLogger(this.getClass().getName());
String pagetitle = "Revenue Sharing";
String navtab = "bloggers";
String acl = "blogger";
%>
<%@ include file="/jsp/templates/header.jsp" %>




        <t:div rendered="#{bloggerEarningsRevshare.msg ne ''}">
            <div class="rounded" style="padding: 15px; margin: 5px; background: #F2FFBF;">
                <font class="mediumfont">#{bloggerEarningsRevshare.msg}</font>
            </div>
        </t:div>


        <table cellpadding="0" cellspacing="0" border="0">
            <tr><td valign="top">
            <div style="background: #ffffff; width: 450px; padding: 20px;">
               <font class="mediumfont">Earn With Your Friends</font>
               <br/>
               <font class="smallfont">We'll pay you a piece of any dNeero earnings generated by friends that you invite to the program... out of our own pocket.  When one of your friends accepts the invitation you'll see them listed to the right... and then you'll be making even more money!</font>
               <br/>
               <br/>
               <font class="smallfont">Here's how it works:</font>
               <ul>
                  <li><font class="smallfont">We calculate your friend's earnings</font></li>
                  <li><font class="smallfont">We pay your friend</font></li>
                  <li><font class="smallfont">We pay you up to #{bloggerEarningsRevshare.level1percent}% of your friend's earnings (out of our pocket)</font></li>
                  <li><font class="smallfont">As your friend invites friends we pay you a percentage of your friend's friends earnings (also out of our pocket, see chart to right)</font></li> 
               </ul>

               <br/>
               <br/>
                <h:form id="inviteform">
                    <h:message for="email" styleClass="RED"></h:message>
                    <h:message for="message" styleClass="RED"></h:message>
                    <h:panelGrid columns="2" cellpadding="3" border="0">

                        <h:panelGroup>
                            <h:outputText value="Email Addresses" styleClass="formfieldnamefont"></h:outputText>
                            <br/>
                            <h:outputText value="One per line" styleClass="normalfont"></h:outputText>
                        </h:panelGroup>
                        <h:panelGroup>
                            <h:inputTextarea value="#{bloggerEarningsRevshareInvite.email}" id="email" required="true" cols="40" rows="5"></h:inputTextarea>
                        </h:panelGroup>


                        <h:panelGroup>
                            <h:outputText value="Optional Message" styleClass="formfieldnamefont"></h:outputText>
                            <br/>
                            <h:outputText value="We'll automatically include a link for your friend to click to easily sign up." styleClass="smallfont"></h:outputText>
                        </h:panelGroup>
                        <h:panelGroup>
                            <h:inputTextarea value="#{bloggerEarningsRevshareInvite.message}" id="message" required="false" cols="40" rows="5"></h:inputTextarea>
                        </h:panelGroup>


                        <h:panelGroup>
                        </h:panelGroup>
                        <h:panelGroup>
                            <h:commandButton action="#{bloggerEarningsRevshareInvite.invite}" value="Invite Friends" styleClass="formsubmitbutton"></h:commandButton>
                        </h:panelGroup>


                    </h:panelGrid>

                </h:form>
            </div>

           </td>
           <td valign="top">
                <d:roundedCornerBox uniqueboxname="revsharetree" bodycolor="ffffff" widthinpixels="250">
                    <font class="mediumfont">Friends</font>
                    <br/>
                    <font class="smallfont">Listed below are the friends that you've invited (and those that they've invited) to make money using their blog:</font>
                    <br/>
                    <h:form>
                       <t:saveState id="save" value="#{bloggerEarningsRevshareTreeHandler}"/>
                       <t:tree2 id="serverTree" showRootNode="false" value="#{bloggerEarningsRevshareTreeHandler.treeModel}" var="node" varNodeToggler="t" preserveToggle="false" clientSideToggle="false">
                            <f:facet name="person">
                                    <h:panelGroup>
                                            <t:graphicImage value="/images/myfaces-examples/yellow-folder-open.png" rendered="#{t.nodeExpanded}" border="0" />
                                            <t:graphicImage value="/images/myfaces-examples/yellow-folder-closed.png" rendered="#{!t.nodeExpanded}" border="0" />
                                            <h:outputText value="#{node.description} ($ #{node.amtEarnedFromThisBloggerAllTime})" styleClass="nodeFolder" />
                                    </h:panelGroup>
                            </f:facet>
                       </t:tree2>
                    </h:form>
                </d:roundedCornerBox>

                <d:roundedCornerBox uniqueboxname="percentchart" bodycolor="ffffcc" widthinpixels="250">
                <font class="mediumfont">Earn on Your Friend's Friends</font>
                    <br/>
                    <font class="smallfont">You share in the revenue even if your friends do the inviting!  Of course, each level away from you that percentage will be smaller... but those little bits can add up!</font>
                    <br/>
                <h:form>
                    <t:saveState id="save" value="#{bloggerEarningsRevshare}"/>
                    <h:panelGrid columns="2" cellpadding="3" border="0">

                        <h:panelGroup><h:outputText value=" "></h:outputText></h:panelGroup>
                        <h:panelGroup><h:outputText value="You Earn" styleClass="mediumfont"></h:outputText></h:panelGroup>

                        <h:panelGroup><h:outputText value="1st Level" styleClass="mediumfont"></h:outputText></h:panelGroup>
                        <h:panelGroup><h:outputText value="#{bloggerEarningsRevshare.level1percent} %"></h:outputText></h:panelGroup>

                        <h:panelGroup><h:outputText value="2nd Level" styleClass="mediumfont"></h:outputText></h:panelGroup>
                        <h:panelGroup><h:outputText value="#{bloggerEarningsRevshare.level2percent} %"></h:outputText></h:panelGroup>

                        <h:panelGroup><h:outputText value="3rd Level" styleClass="mediumfont"></h:outputText></h:panelGroup>
                        <h:panelGroup><h:outputText value="#{bloggerEarningsRevshare.level3percent} %"></h:outputText></h:panelGroup>

                        <h:panelGroup><h:outputText value="4th Level" styleClass="mediumfont"></h:outputText></h:panelGroup>
                        <h:panelGroup><h:outputText value="#{bloggerEarningsRevshare.level4percent} %"></h:outputText></h:panelGroup>

                        <h:panelGroup><h:outputText value="5th Level" styleClass="mediumfont"></h:outputText></h:panelGroup>
                        <h:panelGroup><h:outputText value="#{bloggerEarningsRevshare.level5percent} %"></h:outputText></h:panelGroup>

                     </h:panelGrid>

                 </h:form>
                 </d:roundedCornerBox>

            </td></tr>
        </table>



<%@ include file="/jsp/templates/footer.jsp" %>


